---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-iscsi-bazarr-config
  namespace: media
  labels:
    app: bazarr
spec:
  storageClassName: freenas-iscsi-manual-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-iscsi-bazarr-config
