apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: home-automation

labels:
- includeSelectors: true
  pairs:
    storage: truenas

images:
- name: docker.io/postgres
  newTag: "14"
- name: ghcr.io/x-real-ip/home-assistant
  newTag: d41e77f367c9c4924e898701eca988d9c90243aa
