apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: home-automation

labels:
- includeSelectors: true
  pairs:
    storage: truenas

images:
- name: docker.io/postgres
  newTag: "14"
- name: ghcr.io/x-real-ip/home-assistant
  newTag: d8ec318f3685c1f905914148a822dc48f42b7da6
