apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: home-automation

labels:
- includeSelectors: true
  pairs:
    storage: truenas

images:
- name: docker.io/postgres
  newTag: "14"
- name: ghcr.io/x-real-ip/home-assistant
  newTag: fcf6a554d0fe9b8396af50c68b7014368c4ef254
