---
kind: ConfigMap
apiVersion: v1
metadata:
  name: radicale-config
  labels:
    app: radicale
data:
  config: |-
    [server]
    hosts = 0.0.0.0:5232
    [storage]
    filesystem_folder = /data/collections
    [web]
    type = internal
    [logging]
    level = info
    [auth]
    type = htpasswd
    htpasswd_filename = /etc/radicale/users
    htpasswd_encryption = bcrypt
    delay = 1
    realm = Radicale - Password Required
