---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-radicale-data
  labels:
    app: radicale
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-nfs-radicale-data
