apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: home-automation

images:
- name: ghcr.io/x-real-ip/is-it-dark
  newTag: fc2cf48bb4dbba44dc2a94a2e687cf962a30f3e9
