apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: home-automation

images:
- name: ghcr.io/x-real-ip/is-it-dark
  newTag: c70aab54ab57e625582bbae7d3447c85d7929162
