---
kind: Service
apiVersion: v1
metadata:
  name: redis-hl
  namespace: tools
  labels:
    app: redis
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  selector:
    app: redis
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: 6379
