---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

images:
  - name: ghcr.io/x-real-ip/open-family-finance-web
    newTag: fix-need-to-tap-twice-in-copy-icon-to-pop-up
  - name: ghcr.io/x-real-ip/open-family-finance-api
    newTag: fix-need-to-tap-twice-in-copy-icon-to-pop-up


namespace: tools

labels:
  - includeSelectors: true
    pairs:
      storage: truenas
