---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

images:
  - name: ghcr.io/x-real-ip/open-family-finance-web
    newTag: 51-feature-to-enter-contract-duration
  - name: ghcr.io/x-real-ip/open-family-finance-api
    newTag: latest

namespace: tools

labels:
  - includeSelectors: true
    pairs:
      storage: truenas
