---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

images:
  - name: ghcr.io/x-real-ip/open-family-finance-web
    newTag: 37-popup-out-of-screen-on-mobile-devices
  - name: ghcr.io/x-real-ip/open-family-finance-api
    newTag: 37-popup-out-of-screen-on-mobile-devices


namespace: tools

labels:
  - includeSelectors: true
    pairs:
      storage: truenas
