---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-iscsi-vaultwarden-db
  labels:
    app: vaultwarden-database
spec:
  storageClassName: "freenas-iscsi-manual-csi"
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: xfs
    volumeHandle: pv-iscsi-vaultwarden-db
    volumeAttributes:
      portal: truenas-master.lan.stamx.nl:3260
      iqn: iqn.2005-10.org.freenas.ctl:vaultwarden-db-2
      lun: "0"
      node_attach_driver: iscsi
      provisioner_driver: node-manual
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: vaultwarden-data-pv-nfs
  labels:
    app: vaultwarden
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: vaultwarden-data-pv-nfs
    volumeAttributes:
      server: truenas-master.lan.stamx.nl
      share: /mnt/ssd/containers/k8s/vaultwarden-data
      node_attach_driver: nfs
      provisioner_driver: node-manual
