---
kind: Service
apiVersion: v1
metadata:
  name: piper
  labels:
    app: piper
spec:
  selector:
    app: piper
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 10200
      targetPort: 10200
