---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bazarr
  - jellyfin
  - media.yaml
  - prowlarr.yaml
  - radarr.yaml
  - seerr
  - sonarr.yaml
  - transmission.yaml
