---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-iscsi-seerr-config
  labels:
    app: seerr
spec:
  storageClassName: "freenas-iscsi-manual-csi"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: xfs
    volumeHandle: pv-iscsi-seerr-config
    volumeAttributes:
      portal: truenas-master.lan.stamx.nl:3260
      iqn: iqn.2005-10.org.freenas.ctl:seerr-config
      lun: "0"
      node_attach_driver: iscsi
      provisioner_driver: node-manual

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-iscsi-seerr-config
  labels:
    app: seerr
spec:
  storageClassName: freenas-iscsi-manual-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-iscsi-seerr-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seerr
  labels:
    app: seerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seerr
  template:
    metadata:
      labels:
        app: seerr
    spec:
      containers:
        - name: seerr
          image: ghcr.io/seerr-team/seerr:latest
          podSecurityContext:
            fsGroup: 1001
            fsGroupChangePolicy: OnRootMismatch
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            privileged: false
            runAsUser: 1000
            runAsGroup: 1001
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: TZ
              value: "Europe/Amsterdam"
            - name: PORT
              value: "5055"
          ports:
            - name: http
              containerPort: 5055
          volumeMounts:
            - name: config
              mountPath: /app/config
          resources: {}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pvc-iscsi-seerr-config

---
apiVersion: v1
kind: Service
metadata:
  name: seerr-service
spec:
  selector:
    app: seerr
  ports:
    - name: http
      protocol: TCP
      port: 5055
      targetPort: http
  type: ClusterIP

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: seerr
  labels:
    gateway: private
    app: seerr
spec:
  hostnames:
    - seerr.lan.stamx.nl
  parentRefs:
    - name: private
      namespace: gateway-private
      sectionName: https
  rules:
    - backendRefs:
        - name: seerr-service
          port: 5055