apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: home-automation

labels:
- includeSelectors: true
  pairs:
    storage: truenas

patches:
- path: patch_deployment_zwavejs2mqtt-us.yaml

images:
- name: ghcr.io/zwave-js/zwave-js-ui
  newName: ghcr.io/zwave-js/zwave-js-ui
  newTag: 11.4.1
