---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-iscsi-frigate-config
  labels:
    app: frigate
spec:
  storageClassName: "freenas-iscsi-manual-csi"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: xfs
    volumeHandle: pv-iscsi-frigate-config
    volumeAttributes:
      portal: truenas-master.lan.stamx.nl:3260
      iqn: iqn.2005-10.org.freenas.ctl:frigate-config
      lun: "0"
      node_attach_driver: iscsi
      provisioner_driver: node-manual

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-frigate-media
  labels:
    app: frigate
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-frigate-media
    volumeAttributes:
      server: truenas-master.lan.stamx.nl
      share: /mnt/ssd/containers/k8s/frigate-media
      node_attach_driver: nfs
      provisioner_driver: node-manual

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-iscsi-frigate-config
  labels:
    app: frigate
spec:
  storageClassName: freenas-iscsi-manual-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-iscsi-frigate-config

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-frigate-media
  labels:
    app: frigate
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: pv-nfs-frigate-media

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: mqtt-password
spec:
  encryptedData:
    FRIGATE_MQTT_PASSWORD: AgCUaDivd/Ze+kRqGc/emXOI/hg1ugYGbT1y31hiPulrMBxmBqQPjqdIM0SDwU+cMFVkztIqHQtvQPsDqHZiMm+4X5Ut8kFeV0MBwqtRRubl0It7wUq9c9Oi+czyFI3SXrMxr34V6371xjUMRE6ytwmJpK882asWThTYfqh6g8lTTbwqV2RToBNv3XI4x5YxbYlXCWFE2MJiii2yAIlOCyNz1h/angQQ7EUZD0WXMiPxKRifcHq5R8rvRpO6rKnKbJDS2pX6l5hZedPkEOeme3BVU+ffOcR7pBJsl9hkbuf2YZyIfEf/LHe/N3p18C5006adGC0U9UzhfU6PZaQI7B6YMdV6hmYEuKBNF5FaLJaqZUxk4AbF1n5FamPCCGl9laPj6W1Z7whkQcx+jTrqYjNTMEqqWASEZjPZNIfnmd05It4tfaHEq0jTBWWn6Q5iw0MYiCxpWjt7fQ+Gt87YvD5s4nC3UfseqvMG7RaXvy9lOS1sBxk7Bod6TSRUXPD12S29MBqESLWUmdmCMSBsLZbYpeeikxPVwAOQ4gzKfc4hF8kKMiKt+cimWvfd9F70p4dXN5TAeEMLg81YSaj2Ife9q9BsbFypYta6cinfONoewYOp935PqiREBjK5aA4evLEL8woHXMM5BplqFDT+hZkzNJ6j6W1sm0Ld3DS9cwIeo7gsVlh+Oqs8qmOfyzA+39H+8Kz+uZQt98QwsUI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: mqtt-password

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate
  labels:
    app: frigate
data:
  config.yaml: |
    go2rtc:
      enabled: false

    tls:
      enabled: false

    auth:
      enabled: true

    detectors:
      coral:
        type: edgetpu
        device: usb

    face_recognition:
      enabled: true
      model_size: small

    mqtt:
      host: mosquitto.home-automation.svc.cluster.local
      port: 1883
      user: mqttuser
      password: '{FRIGATE_MQTT_PASSWORD}'

    cameras:
      backyard:
        live:
          stream_name: backyard
        ffmpeg:
          inputs:
            - path: rtsp://go2rtc-service.home-automation.svc.cluster.local:8554/ipcam-01
              roles:
                - record
            - path: rtsp://go2rtc-service.home-automation.svc.cluster.local:8554/ipcam-01_sub
              roles:
                - detect
        objects:
          track:
            - person
          mask:
            - 0.002,0.601,0.15,0.532,0.361,0.522,0.364,0.76,0.531,0.756,0.529,0.425,1,0,0,0
        detect:
          width: 640
          height: 360
          fps: 5
        record:
          enabled: true
          retain:
            days: 3
            mode: all
          alerts:
            retain:
              days: 14
          detections:
            retain:
              days: 14
        motion:
          mask:
            - 0,0.6,0.085,0.573,0.153,0.542,0.285,0.535,0.357,0.524,0.36,0.755,0.414,0.747,0.533,0.754,0.532,0.715,0.527,0.433,0.607,0.353,0.621,1,1,1,1,0,0,0
            - 0.161,1,0.16,0.906,0.102,0.891,0.064,0.966
          threshold: 40
      frontyard:
        live:
          stream_name: frontyard
        ffmpeg:
          inputs:
            - path: rtsp://go2rtc-service.home-automation.svc.cluster.local:8554/ipcam-03
              roles:
                - record
                - detect
        objects:
          track:
            - person
          mask:
            - 0,0.309,0.35,0.452,0.491,0.467,0.592,0.45,1,0,1,0,0,0
        detect:
          width: 640
          height: 360
          fps: 5
        record:
          enabled: true
          retain:
            days: 3
            mode: all
          alerts:
            retain:
              days: 14
          detections:
            retain:
              days: 14
        motion:
          mask:
            - 0,0.552,0.563,0.696,0.591,0.581,0.635,0.534,0.642,0.669,1,0.611,1,0,0,0
          threshold: 40
          contour_area: 10
          improve_contrast: true
      baby:
        live:
          stream_name: baby
        ffmpeg:
          inputs:
            - path: rtsp://go2rtc-service.home-automation.svc.cluster.local:8554/ipcam-02
              roles:
                - record
                - detect
        objects:
          track:
            - person
          mask:
            - 0.35,0,0.371,0.559,0.401,1,0,1,0,0
        record:
          enabled: true
          retain:
            days: 3
            mode: all
        review:
          alerts:
            labels: []
          detections:
            labels: []
        motion:
          mask:
            - 0.715,0.015,0.716,0.053,0.979,0.05,0.979,0.01

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  labels:
    app: frigate
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frigate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      initContainers:
        - name: init-cp-config-file
          image: busybox
          command: ["/bin/sh", "-c", "cp /tmp/config.yaml /config/config.yaml"]
          volumeMounts:
            - name: configmap
              mountPath: /tmp/
            - name: config
              mountPath: /config
      containers:
        - name: frigate
          image: "ghcr.io/blakeblackshear/frigate:stable"
          imagePullPolicy: Always
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 8971
              protocol: TCP
            - name: http-services
              containerPort: 5000
              protocol: TCP
            - name: rtsp
              containerPort: 8554
              protocol: TCP
            - name: webrtc-tcp
              containerPort: 8555
              protocol: TCP
            - name: webrtc-udp
              containerPort: 8555
              protocol: UDP
            - name: webrtc-api-tcp
              containerPort: 1984
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http-services
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http-services
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          envFrom:
            - secretRef:
                name: mqtt-password
                optional: true
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
            - name: dshm
              mountPath: /dev/shm
            - name: tmp
              mountPath: /tmp
            - mountPath: /dev/bus/usb
              name: usb-bus
              readOnly: false
            - mountPath: /dev/dri/renderD128
              name: dri-render
          resources:
            requests: {}
            limits:
              memory: "2560Mi"
              cpu: "2500m"
      volumes:
        - name: configmap
          configMap:
            name: frigate
        - name: config
          persistentVolumeClaim:
            claimName: pvc-iscsi-frigate-config
        - name: media
          persistentVolumeClaim:
            claimName: pvc-nfs-frigate-media
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        - name: usb-bus
          hostPath:
            path: /dev/bus/usb
            type: Directory
        - name: dri-render
          hostPath:
            path: /dev/dri/renderD128
            type: CharDevice

---
apiVersion: v1
kind: Service
metadata:
  name: frigate
  labels:
    app: frigate
spec:
  selector:
    app: frigate
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8971
      protocol: TCP
      targetPort: http
    - name: http-services
      port: 5000
      protocol: TCP
      targetPort: http-services
    - name: rtsp
      port: 8554
      protocol: TCP
      targetPort: rtsp
    - name: webrtc-tcp
      protocol: TCP
      port: 8555
      targetPort: webrtc-tcp
    - name: webrtc-udp
      protocol: UDP
      port: 8555
      targetPort: webrtc-udp

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frigate
  labels:
    app: frigate
spec:
  ingressClassName: nginx-private
  rules:
    - host: frigate.lan.stamx.nl
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: frigate
                port:
                  name: http
  tls:
    - hosts:
        - frigate.lan.stamx.nl
      secretName: tls-wildcard-lan-stamx-nl
