---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-iscsi-frigate-config
  labels:
    app: frigate
spec:
  storageClassName: freenas-iscsi-manual-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-iscsi-frigate-config
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-frigate-media
  labels:
    app: frigate
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: pv-nfs-frigate-media
