# -- Creating PVC to store configuration
config:
  persistence:
    # -- Size of persistent disk
    size: 5Gi
    # -- Annotations for PVCs
    annotations: {}
    # -- Access modes of persistent disk
    accessModes:
      - ReadWriteOnce
    # -- Config name
    name: ""
    # -- Name of the permanent volume to reference in the claim.
    # Can be used to bind to existing volumes.
    volumeName: "pv-iscsi-seerr-config"
    # -- Specify an existing `PersistentVolumeClaim` to use. If this value is provided, the default PVC will not be created
    existingClaim: "pvc-iscsi-seerr-config"
    # -- Subpath of the pvc which should be mounted
    subPath: ""
    # -- Storage class for the PVC. Set to "-" to disable dynamic provisioning. Uses default storage class if no value is provided
    storageClass: "freenas-iscsi-manual-csi"

route:
  main:
    # -- Enables or disables the Gateway API route
    enabled: true

    # -- Set the route apiVersion, e.g. gateway.networking.k8s.io/v1 or gateway.networking.k8s.io/v1alpha2
    apiVersion: gateway.networking.k8s.io/v1

    # -- Set the route kind.
    # Note that experimental kinds require changing `apiVersion`
    kind: HTTPRoute

    annotations: {}

    labels: {}

    parentRefs:
      - name: private
        namespace: gateway-private
        sectionName: https

    hostnames:
      - seerr.lan.stamx.nl

    additionalRules: []

    filters: []

    matches:
      - path:
          type: PathPrefix
          value: /

    # -- To redirect to HTTPS, create a new route object under the main route and enable this option.
    # This should only be used with HTTP-like routes, such as HTTPRoute or GRPCRoute.
    # [Reference]( https://gateway-api.sigs.k8s.io/guides/http-redirect-rewrite/ )
    httpsRedirect: false
