---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-zwavejs2mqtt-us-data
  labels:
    app: zwavejs2mqtt-us
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-nfs-zwavejs2mqtt-us-data
