apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: ghcr.io/x-real-ip/node-red
  newTag: 082aeac0242af5e1eb63f48a6621f5adee84ca77

namespace: home-automation

labels:
- includeSelectors: true
  pairs:
    storage: truenas
