apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: ghcr.io/x-real-ip/node-red
  newTag: 8f72a677db4db7436739d566b2cb047dd9618fed

namespace: home-automation

labels:
- includeSelectors: true
  pairs:
    storage: truenas
