apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: ghcr.io/x-real-ip/node-red
  newTag: 612f5b0663cd47627eddb1307588fb163b4d4211

namespace: home-automation

labels:
- includeSelectors: true
  pairs:
    storage: truenas
