---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-iscsi-omada-controller-data
  labels:
    app: omada-controller
spec:
  storageClassName: "freenas-iscsi-manual-csi"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: xfs
    volumeHandle: pv-iscsi-omada-controller-data
    volumeAttributes:
      portal: truenas-master.lan.stamx.nl:3260
      iqn: iqn.2005-10.org.freenas.ctl:omada-controller-config-2
      lun: "0"
      node_attach_driver: iscsi
      provisioner_driver: node-manual
