---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-iscsi-seerr-config
  labels:
    app: seerr
spec:
  storageClassName: freenas-iscsi-manual-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-iscsi-seerr-config
