---
service:
  type: LoadBalancer
  loadBalancerIP: 10.0.100.241
  externalTrafficPolicy: Local

# -- HTTPRoute configuration for Gateway API. See: https://gateway-api.sigs.k8s.io/
httpRoute:
  enabled: true
  # -- Gateway references to attach this HTTPRoute to
  parentRefs:
    - name: private
      namespace: gateway-private
      sectionName: http
  # -- Hostnames to match for this HTTPRoute
  hostnames:
    - jellyfin.lan.stamx.nl

# -- Privileged pod settings for advanced use cases
podPrivileges:
  # -- Enable hostNetwork. Allows pod to use the host's network namespace.
  hostNetwork: true

jellyfin:
  # -- Enable DLNA. Requires host network. See: https://jellyfin.org/docs/general/networking/dlna.html
  enableDLNA: true

persistence:
  media:
    # -- If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner.
    storageClass: freenas-iscsi-manual-csi
    # -- Use an existing PVC for this mount
    existingClaim: pvc-nfs-jellyfin-media
  config:
    # -- If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner.
    storageClass: freenas-iscsi-manual-csi
    # -- Use an existing PVC for this mount
    existingClaim: pvc-iscsi-jellyfin-config
  cache:
    enabled: true
    # -- If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner.
    storageClass: freenas-iscsi-manual-csi
    # -- Use an existing PVC for this mount
    existingClaim: pvc-iscsi-jellyfin-cache
