---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-dsmr-reader-backups
  labels:
    app: dsmr-reader
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: pv-nfs-dsmr-reader-backups
