---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dsmr-reader-postgresql
  labels:
    app: dsmr-reader-database
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  replicas: 1
  serviceName: dsmr-reader-postgresql-hl
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: dsmr-reader-database
  template:
    metadata:
      labels:
        app: dsmr-reader-database
    spec:
      containers:
        - name: postgresql
          image: docker.io/postgres:14
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: dsmr-reader-postgresql-env
                optional: false
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dsmr-reader
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
              name: postgres
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -h 127.0.0.1 -p 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -h 127.0.0.1 -p 5432
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits: {}
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        selector:
          matchLabels:
            app: dsmr-reader-database
        accessModes:
          - ReadWriteOnce
        storageClassName: freenas-iscsi-manual-csi
        resources:
          requests:
            storage: 10Gi
