---
kind: ConfigMap
apiVersion: v1
metadata:
  name: immich-env
  labels:
    app.kubernetes.io/name: immich
data:
  DB_DATABASE_NAME: "immich"
  DB_HOSTNAME: "immich-database"
  DB_USERNAME: "immich"
  IMMICH_MACHINE_LEARNING_URL: "http://immich-machine-learning:3003"
  REDIS_HOSTNAME: "immich-valkey"
