---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: immich-secret-env
  namespace: tools
  labels:
    app: immich
spec:
  encryptedData:
    DB_PASSWORD: AgDW7KPYuVmt1IHruDB5e9JRNLVN/eTZewqSvN1H0X1XfmGMZr5dB1X1f3uxX4z/WqteGv8hii41k2iXGJHOwEnWDFD1GIBBFtvH/JMNoPwunZ+5qZkDRgnkd/8bZGwQpbf4wYulF6WxvmcnsBbzJ2xXQAPDrmfN5VM2Im+ETaIqvfoBgblJmTMto1xp269CoM+X5t34eJivF/CqXLzUCUKBOyv5ZOFRH+pFUh5Wsrizdd5AjuWOjmxGBY+85OZU45+gLmTYUi+ptslaurCE2iJu2QAMLOZH9FYf9KeE+eYynFiPUegEag3mbANCluqbsvJ2duedSKjGXfg4eGyrvCskX2/H7mUgznqzHf9a0UQJoY9XjB2K8JjkGM/69lYiBf+U5tFpMxlJuOTNPXhNqvX0DFk9GrdTxzSjedfpkrI++7bUeRxRLtG9k4IsIADxIc682yiZPH2WfyCmIbOEkxCXPKNICLfGAr0K17BQM+xJVbEkFD+GD45vAq+3d5F3tTRBJZi914ZF9jZJCZqILZrGHw7VZtvgsXqq56azVUGg0yJL9hPv4gIN9BAcuveZOnN7GGO3Z7/q52WQ153eGm/TWf1qNUAr3TZhV99fFlvPPv7fhcASAKhGG+gWyu4Z40xXVdNSN4dmBt26f53rIw1B3/9pplGuaSD6wpy7ZjehCvpG9idLzFgjvJGrgR2ZyL861wxF3cKFrHxJ
  template:
    type: Opaque
    metadata:
      labels:
        app: immich
      name: immich-secret-env
      namespace: tools

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    app: immich-server
  name: immich-config
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    notifications_smtp_from: AgBN9S1Ww8Vi6EdZlk6jxRfRcyTVjYX+U0sWDE7RJ+B3dYVX3lnEUhoqF2g6OVNYAnDII+WNamBceco06BkWOaMeqkq5gD03xH9HefuY2FzClKmPMsQqdjX3fyvhqrRb87FhfDqWzzitAaJwFshDAChBI8o6pCKvZrk1Abu/b0DrlFy+EFZJ5K+BEpg/qhvmPJIkXLS7IzuRQUUPMPM0VLtGRoeuwZPdcAR1TuStX2z2Rrlw8ILO0qoluU5el+IO6i2eSLDyTi0NVlxcEJojklq0xrml1gHdF8Xqpd6caRWPkvjUOr0MBiGCDJfHirT/gamRlApSdze/30YAqKY9cxvULHuVNjSgE0l/pBxHRjT4SEQ2zeD3tHnD5jq7Km5HMpdbV/7gqHa5PUzmtjKyzQqo+s7BerwWW4FQ8kTKBtDdbHqX0metOI5aqbpUdmmOXHHSg4feJdHcL9fV2u56FOjfwxsSy4I12MpFgV4d10rp5s5brNnUN+WfmCrhQORDmGs9llNqzSmnshrlKj0MhArCJz6lJR1S72GNQ0gwnv0SLdjr5nTecUUwwZKEDe6h99T7C6nNxQCeNFv3F8zForLOBRyCGyuU2JTq13n1Nv3ennppQdEABTGDyQAwMzSF8gBPtHrbBj8UoH9ATizz16hnrn3Bw3zUIgcrTzLgrya8tlII4Hga0/3IrStvmHgVFuP26vi1wJMX2iyYwNJJ+c9iaQ==
    notifications_smtp_transport_password: AgARPIUPOa87Vav4MqwoVFMMQh7p5NjbwMTAMw9GlLI6cEcxzotnZB2zNahMSoQ6OQ3yop4//0Ec7Rc7vJTmUvydEVs7/gJy7xKH/fyrkbqWeeXlwnXH5Pzf8G1NW9iPHZCqLTD27H0AJhC9UV4SZmw6qawvIaSU3LZzmX8BzMAffQP8SdxxA0S3T9qHZxKsv6NOKWvqQKxHl4rPWnNMuMpO5Gb8J0efheGvpuL0RQE0QBgCutwZWpiZ/lOn5992MX8EIwxfBrg/PYiZc2mZwTT9Omk+UoGF63PGYDPkymCMxXNsNMvfpm9+nwQkBHLg6XPfb69nxGBxQi1lGXct8efyzQRLuPzilRerqm2+1r5O/wF7Pwvatek6sJAzGX5VyMfKpBuzXE8vd3QnixlypyQMYyEMtMyBiUWxAP+7eh1itqu3W6G9PCso7QNsdIy2Rd0himn4qhsVnPpvzapvVYOGrVUeo8jkhUnja03nXE2APCY+Gzsl1e75idWWPb3Ytauwp5yu59xwo6LL3HCYD04osOJPVyzXzZM6r5ySJljhIr+UVkq4hBFx2e7c1+g2PTTgCKIw43K8w4cQ3dOMP8Si8+dCxKFe2KJhq7YAUTLswfCRdbj38gQQy+f8rBNrznqXED7NwpbqV+6R4pU34gr+tMdXmuMr+0pMJr5I489mIdXdVKwbsGRM3tn71ZB+FbnZp4/Gen/lYcWAhJhLdFhZ
    notifications_smtp_transport_username: AgBN9S1Ww8Vi6EdZlk6jxRfRcyTVjYX+U0sWDE7RJ+B3dYVX3lnEUhoqF2g6OVNYAnDII+WNamBceco06BkWOaMeqkq5gD03xH9HefuY2FzClKmPMsQqdjX3fyvhqrRb87FhfDqWzzitAaJwFshDAChBI8o6pCKvZrk1Abu/b0DrlFy+EFZJ5K+BEpg/qhvmPJIkXLS7IzuRQUUPMPM0VLtGRoeuwZPdcAR1TuStX2z2Rrlw8ILO0qoluU5el+IO6i2eSLDyTi0NVlxcEJojklq0xrml1gHdF8Xqpd6caRWPkvjUOr0MBiGCDJfHirT/gamRlApSdze/30YAqKY9cxvULHuVNjSgE0l/pBxHRjT4SEQ2zeD3tHnD5jq7Km5HMpdbV/7gqHa5PUzmtjKyzQqo+s7BerwWW4FQ8kTKBtDdbHqX0metOI5aqbpUdmmOXHHSg4feJdHcL9fV2u56FOjfwxsSy4I12MpFgV4d10rp5s5brNnUN+WfmCrhQORDmGs9llNqzSmnshrlKj0MhArCJz6lJR1S72GNQ0gwnv0SLdjr5nTecUUwwZKEDe6h99T7C6nNxQCeNFv3F8zForLOBRyCGyuU2JTq13n1Nv3ennppQdEABTGDyQAwMzSF8gBPtHrbBj8UoH9ATizz16hnrn3Bw3zUIgcrTzLgrya8tlII4Hga0/3IrStvmHgVFuP26vi1wJMX2iyYwNJJ+c9iaQ==
  template:
    data:
      immich-config.yaml: |
        backup:
          database:
            cronExpression: 0 02 * * *
            enabled: true
            keepLastAmount: 14
        ffmpeg:
          accel: disabled
          accelDecode: true
          acceptedAudioCodecs:
          - aac
          - mp3
          - opus
          acceptedContainers:
          - mov
          - ogg
          - webm
          acceptedVideoCodecs:
          - h264
          bframes: -1
          cqMode: auto
          crf: 23
          gopSize: 0
          maxBitrate: '0'
          preferredHwDevice: auto
          preset: ultrafast
          realtime:
            enabled: false
            resolutions:
            - 480
            - 720
            - 1080
            videoCodecs:
            - h264
            - hevc
          refs: 0
          targetAudioCodec: aac
          targetResolution: '720'
          targetVideoCodec: h264
          temporalAQ: false
          threads: 0
          tonemap: hable
          transcode: required
          twoPass: false
        image:
          colorspace: p3
          extractEmbedded: false
          fullsize:
            enabled: false
            format: jpeg
            progressive: false
            quality: 80
          preview:
            format: jpeg
            progressive: false
            quality: 80
            size: 1440
          thumbnail:
            format: webp
            progressive: false
            quality: 80
            size: 250
        integrityChecks:
          checksumFiles:
            cronExpression: 0 03 * * *
            enabled: true
            percentageLimit: 1
            timeLimit: 3600000
          missingFiles:
            cronExpression: 0 03 * * *
            enabled: true
          untrackedFiles:
            cronExpression: 0 03 * * *
            enabled: true
        job:
          backgroundTask:
            concurrency: 5
          editor:
            concurrency: 2
          faceDetection:
            concurrency: 2
          integrityCheck:
            concurrency: 1
          library:
            concurrency: 1
          metadataExtraction:
            concurrency: 1
          migration:
            concurrency: 1
          notifications:
            concurrency: 5
          ocr:
            concurrency: 1
          search:
            concurrency: 5
          sidecar:
            concurrency: 1
          smartSearch:
            concurrency: 2
          thumbnailGeneration:
            concurrency: 1
          videoConversion:
            concurrency: 1
          workflow:
            concurrency: 5
        library:
          scan:
            cronExpression: 0 0 * * *
            enabled: true
          watch:
            enabled: false
        logging:
          enabled: true
          level: log
        machineLearning:
          availabilityChecks:
            enabled: true
            interval: 30000
            timeout: 2000
          clip:
            enabled: true
            modelName: ViT-B-32__openai
          duplicateDetection:
            enabled: true
            maxDistance: 0.01
          enabled: true
          facialRecognition:
            enabled: true
            maxDistance: 0.5
            minFaces: 3
            minScore: 0.7
            modelName: buffalo_l
          ocr:
            enabled: true
            maxResolution: 736
            minDetectionScore: 0.5
            minRecognitionScore: 0.8
            modelName: PP-OCRv5_mobile
          urls:
          - http://immich-machine-learning:3003
        map:
          darkStyle: https://tiles.immich.cloud/v1/style/dark.json
          enabled: true
          lightStyle: https://tiles.immich.cloud/v1/style/light.json
        metadata:
          faces:
            import: false
        newVersionCheck:
          channel: stable
          enabled: true
        nightlyTasks:
          clusterNewFaces: true
          databaseCleanup: true
          generateMemories: true
          missingThumbnails: true
          startTime: 00:00
          syncQuotaUsage: true
        notifications:
          smtp:
            enabled: true
            from: '{{ index . "notifications_smtp_from" }}'
            replyTo: ''
            transport:
              host: smtp.protonmail.ch
              ignoreCert: false
              password: '{{ index . "notifications_smtp_transport_password" }}'
              port: 587
              secure: false
              username: '{{ index . "notifications_smtp_transport_username" }}'
        oauth:
          allowInsecureRequests: false
          autoLaunch: false
          autoRegister: true
          buttonText: Login with OAuth
          clientId: ''
          clientSecret: ''
          defaultStorageQuota: null
          enabled: false
          endSessionEndpoint: ''
          issuerUrl: ''
          mobileOverrideEnabled: false
          mobileRedirectUri: ''
          profileSigningAlgorithm: none
          prompt: ''
          roleClaim: immich_role
          scope: openid email profile
          signingAlgorithm: RS256
          storageLabelClaim: preferred_username
          storageQuotaClaim: immich_quota
          timeout: 30000
          tokenEndpointAuthMethod: client_secret_post
        passwordLogin:
          enabled: true
        reverseGeocoding:
          enabled: true
        server:
          externalDomain: ''
          loginPageMessage: ''
          publicUsers: true
        storageTemplate:
          enabled: true
          hashVerificationEnabled: true
          template: '{{ "{{y}}/{{MM}}/{{y}}{{MM}}{{dd}}_{{H}}{{mm}}{{ss}}_{{filetype}}_{{filename}}" }}'
        templates:
          email:
            albumInviteTemplate: ''
            albumUpdateTemplate: ''
            welcomeTemplate: ''
        theme:
          customCss: ''
        trash:
          days: 30
          enabled: true
        user:
          deleteDelay: 7
