---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: immich-secret-env
  namespace: tools
  labels:
    app: immich
spec:
  encryptedData:
    DB_PASSWORD: AgDW7KPYuVmt1IHruDB5e9JRNLVN/eTZewqSvN1H0X1XfmGMZr5dB1X1f3uxX4z/WqteGv8hii41k2iXGJHOwEnWDFD1GIBBFtvH/JMNoPwunZ+5qZkDRgnkd/8bZGwQpbf4wYulF6WxvmcnsBbzJ2xXQAPDrmfN5VM2Im+ETaIqvfoBgblJmTMto1xp269CoM+X5t34eJivF/CqXLzUCUKBOyv5ZOFRH+pFUh5Wsrizdd5AjuWOjmxGBY+85OZU45+gLmTYUi+ptslaurCE2iJu2QAMLOZH9FYf9KeE+eYynFiPUegEag3mbANCluqbsvJ2duedSKjGXfg4eGyrvCskX2/H7mUgznqzHf9a0UQJoY9XjB2K8JjkGM/69lYiBf+U5tFpMxlJuOTNPXhNqvX0DFk9GrdTxzSjedfpkrI++7bUeRxRLtG9k4IsIADxIc682yiZPH2WfyCmIbOEkxCXPKNICLfGAr0K17BQM+xJVbEkFD+GD45vAq+3d5F3tTRBJZi914ZF9jZJCZqILZrGHw7VZtvgsXqq56azVUGg0yJL9hPv4gIN9BAcuveZOnN7GGO3Z7/q52WQ153eGm/TWf1qNUAr3TZhV99fFlvPPv7fhcASAKhGG+gWyu4Z40xXVdNSN4dmBt26f53rIw1B3/9pplGuaSD6wpy7ZjehCvpG9idLzFgjvJGrgR2ZyL861wxF3cKFrHxJ
  template:
    type: Opaque
    metadata:
      labels:
        app: immich
      name: immich-secret-env
      namespace: tools

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  labels:
    app: immich-server
  name: immich-config
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    notifications_smtp_from: AgBN9S1Ww8Vi6EdZlk6jxRfRcyTVjYX+U0sWDE7RJ+B3dYVX3lnEUhoqF2g6OVNYAnDII+WNamBceco06BkWOaMeqkq5gD03xH9HefuY2FzClKmPMsQqdjX3fyvhqrRb87FhfDqWzzitAaJwFshDAChBI8o6pCKvZrk1Abu/b0DrlFy+EFZJ5K+BEpg/qhvmPJIkXLS7IzuRQUUPMPM0VLtGRoeuwZPdcAR1TuStX2z2Rrlw8ILO0qoluU5el+IO6i2eSLDyTi0NVlxcEJojklq0xrml1gHdF8Xqpd6caRWPkvjUOr0MBiGCDJfHirT/gamRlApSdze/30YAqKY9cxvULHuVNjSgE0l/pBxHRjT4SEQ2zeD3tHnD5jq7Km5HMpdbV/7gqHa5PUzmtjKyzQqo+s7BerwWW4FQ8kTKBtDdbHqX0metOI5aqbpUdmmOXHHSg4feJdHcL9fV2u56FOjfwxsSy4I12MpFgV4d10rp5s5brNnUN+WfmCrhQORDmGs9llNqzSmnshrlKj0MhArCJz6lJR1S72GNQ0gwnv0SLdjr5nTecUUwwZKEDe6h99T7C6nNxQCeNFv3F8zForLOBRyCGyuU2JTq13n1Nv3ennppQdEABTGDyQAwMzSF8gBPtHrbBj8UoH9ATizz16hnrn3Bw3zUIgcrTzLgrya8tlII4Hga0/3IrStvmHgVFuP26vi1wJMX2iyYwNJJ+c9iaQ==
    notifications_smtp_transport_password: AgBJBLC/lUnkO6qYto1mGVqENrIs4QhrPpcE09qHsA8gSLj13ik7ZMZcG8tPFXKdFYcKwmO36emvXL1e41XcUX6wZ6vsBFhNAYpjgN5I8BqKt7CA+Af1Qw/WTU4EXAi9CAEgAmM2iyeQMQiJCOPmOFNJe5ZegKgfjungFhX0E48TSKvIrhrIDBtJXWcl2/uLHalTZCw5IXuuYB0Je9+HH5BP5EiQruWqZH/AEpuEOM69f2udJVoCErMqcakjxwlU25vVgNe7KdrFjPW6DZoewIlu9hPLc5DfmkemhOzSo1v4H5Dgg6y37+VHbbtZKWNpWID9WfJAt4H//e0nISzUbfgRNkeNBaqEnWALcf10wGmBO5T9e7ZiKuKaEOtGZdplKCBmf02okLpaBASWYq1GpFKcqky1yhctrMe/0bWOIppLyYMyGnMWg7KrMlbhHjPnnjE0nuNeMOQhmbhAvXr/kq3Wu4vzgoeoKx7ZA+tjoMLlB25zlXaVjcscx9q+sYJo1ApcXw2NKnstiVG3HBXBOsS+Sw4ysnDxpxm796uCZl3LY65TdZEIs0pRzS4KHHtXQskQPdF5SpfWrY8BWdZXKpOzysrb3hvp9W/T0w0bKCxoZIfKQp/KOQ+eGE9vRfpvUq2FGPzvGq9PYUSM/+MyDeB9j65k/igPkJKJDIxqKZdnSilNMl+XyMFw2F+PvxzJbik3MWlguJE36AQGeyggNeM/
    notifications_smtp_transport_username: AgBN9S1Ww8Vi6EdZlk6jxRfRcyTVjYX+U0sWDE7RJ+B3dYVX3lnEUhoqF2g6OVNYAnDII+WNamBceco06BkWOaMeqkq5gD03xH9HefuY2FzClKmPMsQqdjX3fyvhqrRb87FhfDqWzzitAaJwFshDAChBI8o6pCKvZrk1Abu/b0DrlFy+EFZJ5K+BEpg/qhvmPJIkXLS7IzuRQUUPMPM0VLtGRoeuwZPdcAR1TuStX2z2Rrlw8ILO0qoluU5el+IO6i2eSLDyTi0NVlxcEJojklq0xrml1gHdF8Xqpd6caRWPkvjUOr0MBiGCDJfHirT/gamRlApSdze/30YAqKY9cxvULHuVNjSgE0l/pBxHRjT4SEQ2zeD3tHnD5jq7Km5HMpdbV/7gqHa5PUzmtjKyzQqo+s7BerwWW4FQ8kTKBtDdbHqX0metOI5aqbpUdmmOXHHSg4feJdHcL9fV2u56FOjfwxsSy4I12MpFgV4d10rp5s5brNnUN+WfmCrhQORDmGs9llNqzSmnshrlKj0MhArCJz6lJR1S72GNQ0gwnv0SLdjr5nTecUUwwZKEDe6h99T7C6nNxQCeNFv3F8zForLOBRyCGyuU2JTq13n1Nv3ennppQdEABTGDyQAwMzSF8gBPtHrbBj8UoH9ATizz16hnrn3Bw3zUIgcrTzLgrya8tlII4Hga0/3IrStvmHgVFuP26vi1wJMX2iyYwNJJ+c9iaQ==
  template:
    data:
      immich-config.yaml: |
        notifications:
          smtp:
            enabled: true
            from: "{{ index . 'notifications_smtp_from' }}"
            replyTo: ''
            transport:
              host: smtp.protonmail.ch
              ignoreCert: true
              password: "{{ index . 'notifications_smtp_transport_password' }}"
              port: 587
              username: "{{ index . 'notifications_smtp_transport_username' }}"
