---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-paperless-consume
  labels:
    app: paperless
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nfs-paperless-consume
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-paperless-data
  labels:
    app: paperless
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nfs-paperless-data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-paperless-export
  labels:
    app: paperless
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nfs-paperless-export
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-paperless-media
  labels:
    app: paperless
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nfs-paperless-media
