---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-iscsi-paperless-db
  labels:
    app: paperless-database
spec:
  storageClassName: "freenas-iscsi-manual-csi"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: xfs
    volumeHandle: pv-iscsi-paperless-db
    volumeAttributes:
      portal: truenas-master.lan.stamx.nl:3260
      iqn: iqn.2005-10.org.freenas.ctl:paperless-db
      lun: "0"
      node_attach_driver: iscsi
      provisioner_driver: node-manual
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-paperless-consume
  labels:
    app: paperless
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-paperless-consume
    volumeAttributes:
      server: truenas-master.lan.stamx.nl
      share: /mnt/ssd/webdav/paperless-consume
      node_attach_driver: nfs
      provisioner_driver: node-manual
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-paperless-data
  labels:
    app: paperless
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-paperless-data
    volumeAttributes:
      server: truenas-master.lan.stamx.nl
      share: /mnt/ssd/containers/k8s/paperless-data
      node_attach_driver: nfs
      provisioner_driver: node-manual
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-paperless-export
  labels:
    app: paperless
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-paperless-export
    volumeAttributes:
      server: truenas-master.lan.stamx.nl
      share: /mnt/ssd/containers/k8s/paperless-export
      node_attach_driver: nfs
      provisioner_driver: node-manual
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-paperless-media
  labels:
    app: paperless
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-paperless-media
    volumeAttributes:
      server: truenas-master.lan.stamx.nl
      share: /mnt/ssd/containers/k8s/paperless-media
      node_attach_driver: nfs
      provisioner_driver: node-manual
