---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: paperless-postgresql
  labels:
    app: paperless-database
spec:
  encryptedData:
    postgres-password: AgCaznYATyTFFUCbfEB1PqW9zh6Xk3CHyzx7kFqaHu+/3LLbjXTzTWdNxkeo2VMMxlhEcVrwH8NX8NJVp5PtRPWsvf3Jd53Dix1QZ72J0hT6bj8evQnmEvz2U4yR4XZV7qhjQU+By7UcsuE5Sjd/m5GWoULLARPi5fswnZOCN5rY2wxpjnf2UdGYOjBucU1FwZEcG0VLdo6Mg0QNZg2D//5ULyw5vfwdwBy9BPmg2Qiie44VDBRnC9LK7UTbJ/jmZTB9lzC3j6yakWxzXVvCZzYomd6fBxGedkzF+4unLJic5WH2WWSMp2znwXID4V5kK4cTb+xVpN+2woat08FaW3oGDGixwnWBY0Wv6AWWluaVMzscQvdw1IJa+VOzkr5UJ9uqZCLQTA9e9Mib9sxR0zcbmu1QxGn27kQgSPLl9vGXBBu6kl53+X7MpH46GW5Bx3nhqUln4Kxm3ydvwaf1eJfANPev1bJ6YdE47T4rEa8dePZegCOtlxuSoOTTc69hguuMKyuDj3+un27VblULjMmuZu7qFxalUSc1pZOfxjc68Et5OvuzC5YUFuvtvsF6CTYGI12dXqg+rRqBI9ACiVpR6Xm1w5Vy+nbRzCvksoCryiqtbyuTVmzJ7IkO7t6MOBJ5E6YUItDQibe5l0LWybodfPhj+UFm6oPSx4C2cJ2rwwb6S8yB+8bOGB4U9iMvku4ZUyCy+n6P/yQdoVfOWg==
  template:
    metadata:
      labels:
        app: paperless-database
      name: paperless-postgresql
      namespace: tools
    type: Opaque
---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: paperless-admin-password
  namespace: tools
  labels:
    app: paperless
spec:
  encryptedData:
    admin-password: AgA4ybCtOvoNFSR9uMfjJY0UwGQcT+ZQtqpcypdjYbkJxBXsjWQwG4KXRhBJ3lpYrWPy3zNkiiYCmIu/W5VqRT4edcgv2vwxT8Pwy2s4Vsn2ZHvgqKY8Nb+OPBIJylwsI+GVNH8AwqpjvT6z0yQNflIVZVzHcSMUwzhRKVObYSAIY7+lMjdIyY0slZJurQyVJuoTucv/QQ/yqSv4RWFUkXsw7XrWLHCEyIsJSExK2CE4C+rEK5TDBjxKesT05Ium5GdEaqIHeChZfED70MfDJnMemtdTPkKASa+7T0uSqyiAkV8J08BfUijc5b0hsgi87ZB451koRng2HrN3y1UGTJF+vGXx7hop7id2hKi4zxjmLkP+Uu9sved71UFEuHcByNCiVLG6uFPq4QQphBatVl2KxQ1wAzY2TNz/PHDDImD0e5xiEvYrdZMvymOgNs7sw1teWy1kJZd8Pnkd2a4jTzaHZ0CS3gC5txlRC1lpgWiO0WLp8VGVPxTuxrM5WJbMEJ2cgZ7e7E3lzOp2Z12ywOJ08alKceLFCmmYD83PsQ4oPFNQrl7R09IEzoX9F99ZkLgNcRERTOW7E5AlGbjEnw6tg33JAYwFjjA31ZYdRqH3TFIdwK4BjC5U/OK8AL/A7FJN2asyTO/S3X/1u/odFPlx9H6ADUbs2Qd+X40zfxsn1Hz3xx4s7ISI0QIJXhZW5KjJCHkwj5tvsv8P3xw4eQ==
  template:
    metadata:
      labels:
        app: paperless
      name: paperless-admin-password
      namespace: tools
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-secret
  namespace: tools
spec:
  encryptedData:
    PAPERLESS_SECRET_KEY: AgA/R0ujXEPZm8f4YVhh12bhdYJdG1SUe/haUuI0e3gl9SN5QQ1YCvdqXXnO8SIJLeszdbaWgUbx08tUBafJgSNyVhS3Tykm0jIHbbIboHGT4SAQ9nauK1vTopOHfF1vPmqOIIXhd28nEvSTYfsDVAhTtSkKBT5WU1w3W2z20YkBAlWg/vUho8ZAMcMgC1wxYTUJ/Jw3sbUR6H7dpw+EhVX5nuqTn0nk+YSuGDfS9OQxUgUjoK4jxMg/ix3pTSHW/xG8bQKAqpysXXYEps6eS1I1b7kC7E3OOh5Xe/PEkJpzgzFVCxtGLf9rVVHfdHFNDv82XiFvryj1AWs6DPJDVvrJJu1rec7A78TbfNW0qdw7f1mBHl9bvbcGVZWbxKVqBDjBsuzj69gwYbob6N8yh0mBAqugxbE+9H0X+X3098fpCZQAx7kFC9YTaCDzelPx6JEZITP8vQCWwQyEk1btzOpTGh718UKodUIoG4fnLWiNA+yHNS1E5RxEIWW+4encHvTbw4BrXhS6H4oMbZ2EEip8MADLt5QPEioj+9IIahRbpU/ze4XUIMYhUhlYF3WP9KwzlQon0l8F29W+Pf1Nj9bo9d/hMVIxPpSmy0gRZCwvXUglDrhEPFEsg5N9asgkEwrg4uC3gOD+T12xAY2mx505ek+HrW0tXwcltG5dIq7t1Um5YHsVkrij/Mmg2iObTs48oExmNUCvmHQz+fmXw9Y1bPzST14HbVK+tBOLwpy2U1AiwdUHCexq
  template:
    metadata:
      name: paperless-secret
      namespace: tools
