apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE+jCCAuKgAwIBAgIUcw7Cx6dasAXFNLWl+2Mpr2emOgMwDQYJKoZIhvcNAQEL
    BQAwFTETMBEGA1UEAwwKIFN0YW14IENBIDAeFw0yNDEwMTMwODU5NTNaFw0zNDEw
    MTEwODU5NTNaMBUxEzARBgNVBAMMCiBTdGFteCBDQSAwggIiMA0GCSqGSIb3DQEB
    AQUAA4ICDwAwggIKAoICAQCtWDD4b2cAQLVF7mR9NMKQuhaFBcFSbcUgV2q6pppc
    Sn6XlBkpGaH7tbZlO2O0V1Td7vZ0eWowdC4Chk2s1AEqelExLLBa+0jRxiPqWoby
    qF18bif9yGbIJeMQ/rWQAGKsWSoNXC3OrV6IA2C/snFAFSVJ7GoTGT/19WYkHoiM
    UNU4t1PLYdSN0hF44PT8PmCPhnK8pDEexQ+Ir4jXIWLJyX8zYBs2W+4fE45GaSBY
    lpw57cecnbegO7PiGIfDjQhAYhNdnsVT11+/V6qawVAW3ldUxQD+gku+b4bL0cx8
    HU1xqDTnvPhuRtPvWKqMToZlYplw2cq8GGIhPotaxfeSPzNzIk4Re6XdtkXlIeuw
    J3WrOW3KYZfU2eXx70vHj/VUtct28WzP7xIejeqIRaZE2kyk2QTBv8zDQjTFGpj3
    M6zZpitkVo1590vKqRJZFX4DLtn9K0OBPxlTay+iFwIVH+B9I2cXz2fSe3kFI1mr
    6r2mGE4C6CdbTLRdie2nUZSOLYkuK//NHGYGHrDujNTQGPN9djl2XXWwDhnqL2z7
    xL+Iug2Fo3KBs4PXX40t9qvLNHyc2BSWJsW9M+TZnC1fSe4xBr87EBcT3MqH6nSx
    0SP64fegj0QisLNmn8jqiEq2p8HTTPlCxrCg5McKSJBPV+wmUNChJZHX5salULth
    eQIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAgQwDwYDVR0TAQH/BAUwAwEB/zAdBgNV
    HQ4EFgQUwlT1yFNsgNElK/T/qIsTNhnsfsIwDQYJKoZIhvcNAQELBQADggIBABGs
    smpEIEMH2R0AteXZq3KazspkstRfWo4TTFTpBLK9aMOQ+SmV+pVfq094J3TgSHjh
    zFOTuV6T315ATl1rhTaFBixSTWRPU5xSc0aVPtLtlWqOdLR7ktekByC9kDQs6Wtf
    AMznJeFqSP+EAnky7+jhNRPVqz1L5SBV/np6m+jCVHXmNtZQAt+sMQoTgww5RUFQ
    Xr5kSaFp2mOVxvXMwmxKlKXbvDfjxYjnUYQJGvMfisyugj6H398QYdRju2QHFxsc
    CbDjK7vq8EvBp3HR7hdWpXN3d8ldeS4/Lynh4hE6kEgIx3xUlc5Mc5TRb9KPVEsx
    bD0sg8/FDq0AKuy49lo5Tr+SNAEoQXZeff5VzNmNO82w/gVACWkdsx4ne1/sOr/r
    nHkslKr31W4iDLgd2eMN5dLbmbBCxixxuDUDFrLNnLGF1nl+3YgfOm4YrNWs/KZG
    tzaF7c8k0EIA1OO5muuD3SGv0g1F7JZKhde85X/4FfH3AsFd3oyfIAZK30LZ6RsZ
    QLaZ0xofKoVuFMCu9PWDn9y5JlLg/8nGB7+PtqCF1VEqOXP8sjs5XMUivi2osszW
    CqYwVU4Kpm7yMGm8Gnzc6tySZwItdyFK+3CqXKF9QNTH1LgeKd0t0KuHuse5nEgy
    P616yAVWs/5MUriT/VXQVUq8aystRtW74AJJui+j
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: stamx-ca
  namespace: tools
