---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-iscsi-radarr-config
  namespace: media
  labels:
    app: radarr
spec:
  storageClassName: freenas-iscsi-manual-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-iscsi-radarr-config
