---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-iscsi-radarr-config
  labels:
    app: radarr
spec:
  storageClassName: "freenas-iscsi-manual-csi"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: xfs
    volumeHandle: pv-iscsi-radarr-config
    volumeAttributes:
      portal: truenas-master.lan.stamx.nl:3260
      iqn: iqn.2005-10.org.freenas.ctl:radarr-config
      lun: "0"
      node_attach_driver: iscsi
      provisioner_driver: node-manual
