apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: home-automation

images:
- name: ghcr.io/x-real-ip/esphome
  newTag: 3334b72e48d32d280c0075c0f1a3f81d9da9a641
