apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: home-automation

images:
- name: ghcr.io/x-real-ip/esphome
  newTag: cc9ebb525404092c04cb2cb192483c089ec7c043
