apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namespace: home-automation

images:
- name: ghcr.io/x-real-ip/esphome
  newTag: 745493642ff72031dd7891fb5f1ca49c33abe896
