apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-iscsi-postgresql-db
  labels:
    app: postgresql-database
spec:
  storageClassName: "freenas-iscsi-manual-csi"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: xfs
    volumeHandle: pv-iscsi-postgresql-db
    volumeAttributes:
      portal: truenas-master.lan.stamx.nl:3260
      iqn: "iqn.2005-10.org.freenas.ctl:CHANGEME-db"
      lun: "0"
      node_attach_driver: iscsi
      provisioner_driver: node-manual
