---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-manual-democratic-csi-node-rb
  labels:
    app.kubernetes.io/name: democratic-csi
    app.kubernetes.io/instance: csi-manual
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: csi-manual-democratic-csi-node-cr
subjects:
  - kind: ServiceAccount
    name: csi-manual-democratic-csi-node-sa
    namespace: democratic-csi
