---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: csi-manual-democratic-csi-driver-config
  labels:
    app.kubernetes.io/name: democratic-csi
    app.kubernetes.io/instance: csi-manual
stringData:
  driver-config-file.yaml: |-
    driver: node-manual
