---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../radarr/overlay
  - ../sonarr/overlay
  - ../prowlarr/overlay
  - ../bazarr/overlay
  - ../base/jellyfin
  - ../base/seerr
  - ../base/transmission
  - ../base/media

namespace: media

labels:
  - includeSelectors: true
    pairs:
      storage: truenas
