---
kind: Service
apiVersion: v1
metadata:
  name: whisper
  labels:
    app: whisper
spec:
  selector:
    app: whisper
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 10300
      targetPort: 10300
