---
kind: ConfigMap
apiVersion: v1
metadata:
  name: webdav-env
  labels:
    app: webdav
data:
  TZ: "Europe/Amsterdam"
  PUID: "1000"
  PGID: "2000"
  SERVER_NAMES: "localhost"
  TIMEOUTS_S: "1200"
