---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-iscsi-protonmail-bridge-data
  labels:
    app: protonmail-bridge
spec:
  storageClassName: "freenas-iscsi-manual-csi"
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: xfs
    volumeHandle: pv-iscsi-protonmail-bridge-data
    volumeAttributes:
      portal: truenas-master.lan.stamx.nl:3260
      iqn: iqn.2005-10.org.freenas.ctl:protonmail-bridge
      lun: "0"
      node_attach_driver: iscsi
      provisioner_driver: node-manual

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-iscsi-protonmail-bridge-data
  namespace: tools
  labels:
    app: protonmail-bridge
spec:
  storageClassName: freenas-iscsi-manual-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-iscsi-protonmail-bridge-data

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: protonmail-bridge
  namespace: tools
  labels:
    app: protonmail-bridge
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: protonmail-bridge
  template:
    metadata:
      labels:
        app: protonmail-bridge
    spec:
      containers:
        - name: protonmail-bridge
          image: "ghcr.io/x-real-ip/protonmail-bridge:264547db870059df134a8c19d3de768454051ade"
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "while true; do sleep 3600; done"]
          resources: {}
          ports:
            - name: smtp
              containerPort: 25
            - name: imap
              containerPort: 143
          livenessProbe:
            tcpSocket:
              port: imap
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: imap
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: protonmail-data
              mountPath: /root
      volumes:
        - name: protonmail-data
          persistentVolumeClaim:
            claimName: pvc-iscsi-protonmail-bridge-data
      imagePullSecrets:
        - name: github-registry-creds

---
kind: Service
apiVersion: v1
metadata:
  name: protonmail-bridge-smtp
  namespace: tools
  labels:
    app: protonmail-bridge
spec:
  selector:
    app: protonmail-bridge
  type: ClusterIP
  ports:
    - name: smtp
      port: 25
      targetPort: 25

---
kind: Service
apiVersion: v1
metadata:
  name: protonmail-bridge-imap
  namespace: tools
  labels:
    app: protonmail-bridge
spec:
  selector:
    app: protonmail-bridge
  type: ClusterIP
  ports:
    - name: imap
      port: 143
      targetPort: 143
