---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-iscsi-protonmail-bridge-data
  namespace: tools
  labels:
    app: protonmail-bridge
spec:
  storageClassName: freenas-iscsi-manual-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-iscsi-protonmail-bridge-data
