---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/x-real-ip/gitops"
    path: manifests/envoy-gateway/overlay
    targetRevision: HEAD
  destination:
    namespace: envoy-gateway-system
    server: "https://kubernetes.default.svc"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
