---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
  labels:
    storage: truenas
spec:
  project: default
  sources:
    - repoURL: https://jellyfin.github.io/jellyfin-helm
      chart: jellyfin
      targetRevision: 3.2.0
      helm:
        valueFiles:
          - $values/apps/jellyfin/values/values.yaml
    - repoURL: "https://github.com/x-real-ip/gitops"
      targetRevision: main
      ref: values
    - repoURL: "https://github.com/x-real-ip/gitops"
      targetRevision: main
      path: apps/jellyfin/extras
  destination:
    server: "https://kubernetes.default.svc"
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
