---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tls-certificates
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/x-real-ip/gitops"
    path: manifests/tls-certificates/overlay
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
