---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-iscsi-home-assistant-db
  labels:
    app: home-assistant-database
spec:
  storageClassName: "freenas-iscsi-manual-csi"
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: xfs
    volumeHandle: pv-iscsi-home-assistant-db
    volumeAttributes:
      portal: truenas-master.lan.stamx.nl:3260
      iqn: iqn.2005-10.org.freenas.ctl:home-assistant-db-2
      lun: "0"
      node_attach_driver: iscsi
      provisioner_driver: node-manual

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-home-assistant-config
  labels:
    app: home-assistant
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-home-assistant-config
    volumeAttributes:
      server: truenas-master.lan.stamx.nl
      share: /mnt/ssd/containers/k8s/home-assistant-config-2
      node_attach_driver: nfs
      provisioner_driver: node-manual

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-home-assistant-config
  labels:
    app: home-assistant
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-nfs-home-assistant-config

---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: home-assistant-postgresql-secret
  labels:
    app: home-assistant-database
spec:
  encryptedData:
    postgresql-password: AgB/gql6IjO58KNJftBGh/GrgetX8HqfV7IkHkHh3nhpWllutiweY/53Lhuq8P09jS+Sf+M38qAjAFil2G0Y1ttvRNPmu3NGoE370mAdHi1EjcRGRM4tCAXFCmXV6lhsTjn+wUeuiHIWf/2ZHoik0TeLDBMhqfGcc6Fg9+qH5F9iKaS50n1xuUM3G6TZ3u9UI95/uVPrqKJzRBNL4gT6yeYWEgDMM3K90pzopzYpeDV0HgLJjRqJmo+G7OPzVcrIiFT1C9p/BW251KdG18UZZr3o8Dwt4zEWKdRmeLkw3ICrOIbm0c8pRNf92yJxa/rRgd62xaTEP+0sr/S6mQkibNVSqKyhwF2qBBgPcaLsZEQCiNbzN4EhrBef+jXWAzRbUtnCCakPsBji+7ffTpbWX9HMr22thg+5a/TFLLpxyV5WGz4hQuFAx1sjgcmsvl3oAlP+i5VbxCEaUUAdpJyKenkrcy6f/SPjSfRsJHT2ebxi1sYfOzdp95UkaNc9NmsF9vDJABQsInAh6utOkzHRgXmTQJkztPp/urqO0hGLOJVAdeweTgt1xMzNExcaROdo+wq3+Xbxb7tWYikvHFfojUwHwIzbQHzVrYX96MdTIWAFPUsgnv1TnPwZ21NhN1p5TSWWdh6aIemz2WVspsqR8tN3GF2dpKf5TrifVIVVv6Mpy2IUdKNHIcSuU2PjgUEVT79HCrpw5SW54u48wV6NpQ1ISfzWirSq
    postgresql-username: AgCz0MGnhxW277J1TR1M6OiEZkiXOnRPWDt8YH0Z52DZAsRyzkQVNLAUsCYGqOrAKHIhfrX/xNBJjFsx69ATj4mZf9r8fcDBKH6Wu08EC/RTGoQNf8tiLaHndtpCkgdd9yA4XdFQ0j/UJXTyMEXcp7av/3JEHvbpXhkLwEsWYMcx+heH+d38edJTpWAkmNVVUdVonxkXqsy3NKjX6R8G0s8mr15/T2/3gf7EkZ4kRAOSx3obzT+fbWK55BK29oOAMGIj1plnFunogNZT94HVM5m5dv8PI1Uzrqt+h0F2BDSiiJDSESBgACmzno6g72JsP0Dpax4CAKsEv/4VNCoc6VXRKCWAI3a61BuBNf+8+XojBvl5eIx+vYdAE0YvqNIKfplGdR1qhd7iTB1VXE6S9gpqcC2Mm8QQn50hnHDZUi91d7wSrpBgbeA54Z+MXBUCRQSccLQPn08HNtWIm2XPloV6fLK6IcJHpin7DOYtrU5fTiILnhokHKaHWnM4snev1wF+wx9uWi+EWmfxFQSrg/743Z/pjAxIsN63td9YggG5NZahW+yNsw+j6FzbHHBpakYXOx3IK92RqEPevWduaol5GfJAT5Uic5rfnfXUYy7fV45zt+uMN61W7lSZG9S+gMszf+BxZlcRIeWvBXNF5ofDlN8itwyQ6tETGcSBG5tl3+SKQIZ/0cpUOrAIG3jJ3L+nXIJfCh5I2q+v2WNO8Q==
  template:
    type: Opaque
    metadata:
      name: home-assistant-postgresql-secret
      labels:
        app: home-assistant

---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: secrets
  labels:
    app: home-assistant
spec:
  encryptedData:
    home_city: AgDUbLU7L334basktEdTU5hynRJUhT7u/850mkvKP/EXIgtzpZTwkQCnaFQRQAhFKVwjvlcCqaHxGCVfjg3F2kGivIamRxlDKt2FF8kVQHm1cYuqn708CjOrPOvlUm/Yd+GBNE30T7c5I2YoEizKhLsZjf8zaSNsv9BEscgE/dqRCSDgK9xcurdOK1TY1foxh+1UuWjpg++H4GHnMsuyJsKE2HnyrZ1vcG54l2usRpd7d37rkcmihtywcHs8PSBLqydIjQxRMrYtnTHwtC+ZoxLoqPWjjpBZ0ndNlGcBKpkt2e6ypR0vgCmHO2RE5H3eeAS1PqbWBfTCRsPeCCKiPDLx2IZlCcIdWomBgJ2tk+UzPWRaYKYwt3Iv+3+AB78kIiycPsAQNTpJgs0JWhVjx3kA42eVI71rNAndbVffofs8CYihhQSuK9ZEnna9gKPoDM80HWqQyRX4rgdwwS4xsuil1sWXWF87tn9EMmxh/ox2sBbJWxo3FnTe4z/gBD7k3zzAhOxbPh1noJCRvOBg1N4tJ5fz/8JAkwzF0tkI1AIsnqoiOyBlvA4wzAFrUf+EJFYnArpvj2P2W9sajoTvizIG2scYaLCl5hYdextwzmLki+G9+PPGVoWmHT8x9jGjeuZj4eHMRS4syc9Hx2tkMdPBqq07G6wzdy7cWAPGMUR8zJpUABgWXC01WX2dBbXZSXcUyso=
    home_latitude: AgAXfKHiBS0dIHRoODyLtSaYGwXSw1RfuDeUepGyrI5VaMiboPOo6pOLCspv0ObQMA1rV2N6UZR0IaP0KdFZiWC1dYv18PKchb3KROjpYtoL2MxAlcQ+Ua2MaUUqLM6rwt5Sism5A3g2WO6HqB2PK7DTp3+6XhhzAajMpHZYCez/ZN6XqpW2x9PIeEWQyd+DjqoFyK3UZH8Wrg1Xj0AK+OZjeMG2wdcLdfFUbbTNXuAujXmgfSnKEEIuoL8oSTsWeGJAViqUiw4uSCfLCfLnMpAVMJ1xANXmj7rhCBjL8R31EbtMpL4Jw5q7Lt25qOnudGYzEoZifS1mUjgWAJq7pUkVb+x6IMCoLzfMQKCYUapG8oEbSiQJBNw4gqeUhPmWJViVFAB1JYNG6vDFUuhJJYjMAq9jCVWKALlk/lERCNTvZX0JIN/jQNe7H+EOorS25JjJZnmft3IA+2+vVti8rhP0gKukzvUcdvAR4bl9pDTrw1hZFBDGTZXuYDHEzRnEKMevgYiHwObtncgl/dM1TZCo7fACZGlEMzSSXP0ZnubGjqT4iBoyWAO/jtQ16oyICOWr9VMMAmBbEMTf2ljkRQJRPW18PXSHSUwmV1LucYZxrZyxUrt9qSXLzNedbVd868+T9DOdYFA/1MxPCIt6BaS87rTtCykNYY0jClwNRT8u3TbOrjt9rLcR75Pez6p25SUwkYDMPAoedSQ=
    home_longitude: AgDHcGDimGbOFt4MiFLfRMVcapPaELs5ltNKz4H/KhmppaezkxbhCoCOsSqpXlZ1GN0mofznsfapMdlJxCojOl3D7AL9NgZmE3UFnEje46Lu8LCUdLbHvzXKUY9X/LIh4rfsxFvFfUqSHqVqJhndf+8lXdhPU+/o1wImQ1IAS/CBpj7/Zp6fri1cZMVcqYpops8kqf9Ny2r4ZovDkxV13zaW14bKG8DcAD25R0Bs+2rVhd7qckXGCZfw7eqxJdQu94guS1ohTvMoM8mIj7wUMIB6HamI9XO0az/lmDiKkYg9UNPJrkrqzHIVQcJVEEeosnjXWYeNwzF8m0kjlfcXNEGWronhns3eirC63lfKX/l+CWvt0l50tprJee3lwmor7fGCT93/txCGO16nABOYnOxPNI69I/MkfbT+ORwRsDZV6isgdWH6aUuRzLtEpckxZRrYhdsR8EN3KAI7ar/1dqKjxhYIvAIL2axAJ7gjhZeQkMNnRjT3EZDw4Ik0f7ws3bT6Ryl77FIxw6ntdsyM7D058wWRE5Hu0kbtieItzmqjCqaBPRzhZPuR47OdWMzTJ3ax8zso8yGS7bzNrNIpae8fRuy8o/ccVXwTukTRLpPVUmTIwVnUXqIT0XhYspFfkefjIkjInfuGNjjdjeBHV+rOPDQpw94LMu0/xky2+y/BI63yPvlWkvw7yOidl332mDk3peg42uWvjA==
    home_number: AgB6U94NdKzDSwIlIhIRLbo8Jwu4gNJxGv2Wbyj8dILUIFwcPGwMMAUmoAtIW8gfLjsKXgYCZvzOfQpdOWqk6IK82xdvX3NiqekK+8CjexbsqcsrD05hAdFi+xaC0iU4OopSh2BTwlwlE77HPPFlzvzOiDTJ6XP5q2n9AfSl0fQR0XDhKTJ26HGi30nprM88F8ajn1RDQF/ZPFCmbFmvRgc3zRFckvF7rTYRdONpFP9l6PpNHiR8JrP4fts/q6tZDIPAvbb3jKuFBCEb8i9qCVOlGFtXB5ynRKFejyxwbibba5jZxlWn7KlN05jqFFi9A1MP0QaJvS3x5o+/7cU7Daw5NCJi2+hISLyEFmBQGSS55GPoB6la5krmt/jpczX3uv8dKKd+9Z7cHxn6a1hX3BVXkcwuPurXuPRCL0IpvLcmGU9dv1IHDvf2gqQIKW72y2xUVhHqZMYE5U8N9z5zBr5r7OGZINXTgPekSzKAsUpsBBYbv8cXPZ35MliaZHErZdDiH6wr4jHZgza3iE5CQqUOqA1sE/4yGF3Y1T1vZdYM6+3hmrlh9QazjQSbs+nk7J7jAZkH87dBcQhaoP9WEbLmp6Be32rAod7f7nWRvCHM5/Twx/IvhusTe4PWC/PgIQrOYi+jjLAV6P+FR3jJAFB3QlPHgsTdwsFxA0BmhDwVSPeng/v1rTy+8QeCKdt2p8J2
    home_zipcode: AgAKbN6Rqg98xRpgqr9DuGrNaWrap1I5TSquM9EZ6gHmf50Uu87nlgeAbNeGkhdKCtPgDwXg1A/khNwizOgKPrqdCRdS9GZUdtF6k9paRAvHBTTE9PJh4DbCMVO81psgwMBVfCdda9O7vYnSmSlS6ZND1PMV2BmV7/bic2JaJm0c4D7rZB6PXw8ReMWH87VK4OQB2Osl38lo7SCuSQmMycmIebEz7U4akQskhwC3uexnjhvIW+MshTJG7z9eMfbG2HhH4QVdbgbxgxeGVyLForLXmw9h6uqGa1flcH7rtI6CBwS2dmPXjy0bRq3Uxs9tf/LTMhr/CPwMhADRlFNRcRddexS75wdYrtIIn9lGmEDLD1Xi5C7WQOGVc9jnPpQtxvqG66QvhUzSTsydSPTyra9r0ACsxnA4o4jjT9/kwEucmZM4d7YihCwNLMGpPfS5aXXtWjaONknBUsIIq4MDpgcnySTxR53mqvO/5xK2Ua/6glhmMRik9jrBkKa4I0qv5Hy7jmEIk86vuS8X6O1DGL/zBPph/ftEXcQP1fREIXPzPdPph/SDxx4DLxK/kfSQX2w4+iOqOh9+bm/qrei+m6PrVJV/C9Oy52Wv3g2RJ19BSAFDtbfsQkDTK8rWwXAmHucPiFzxVwmHKGwkySMF+jtOAW2SYdga+WqZpbYgBKzUKxWVfNDyrXoxDE+wZn7x+2MLReayS20=
    postgresql-password: AgDA8sWjSYFqt9ARyGtqNDR7iJ675Uyxe4DohUDOc+8ztHILld5QHGUneUmOZG7kCiiHxQpcQyBB5KAhG+VDkWol6swtndB6+WtNxBGt/elE44OyChnSSoWL9VpdZENtEK/cYqoiQl1ep2jdhDI92/Cjo5aiAsRnFHSXmoIn1Qs0xTxC9eodHD8iEN8SSrSjfhK27DeUMmbxut3Qujkb52W/Otx40FKZ5syuU26G4m516cvzTDwmayJUS3p6ma4c7AYo2eeEW/cOoh6xRIS1iYmIS9pqiqv1QzC6ZCWWXo+d3zfll624/fFFkp5bWuB7Em1JvGW9jg1jeSaeHCZZuLjikKe5/6E7P/yiodTLJOxot3eSkHwqoV56K1D0+mCBtABfJAVUJf64USXs2JieiyrFOx4ZLRBcTbHZc2cpXG6h6/NaK5Kn+bKpEkcWFDKPXQI3UK/+fnpPobfQwVjpe24nrq2ueOr4aEkMjr00V/HKIl+t0lV7Tg0xgrza65iw9cTGywy4ZGSPgDqEC9BxKlAefhcWFSf17eD9M+tiHexs140qbBlf8T8yWav5HUzk9CrDqGGMYX9Ul9azEYs2UOpeejfpqoF5Om3sSxpkFNJHNVIxdzwcxKzz/nXTOfUYmAXQ0liuhHCkLO3ZXKSm3hYbBA5YD3+bluRSvSf6i61Kij/uYYHJylPG8RZwprAMwrb5U5UDiU3mkVXNZx9x25Lo6mKknfe1
    postgresql-username: AgBY85PRmsngcYe5yLqVl6mP2C/kKVmNWKjl+znt15TAx5ZPf2KVIE5UbG69ArqHW5kj/N+yDoClGdV6/llxbCR8IpLj5tGH9ng9y72HCBnJI4EAg3lMM1umTlkxbSCdBMO14WiMhHO86mL1jalzWDHWxMP8Bye9r8fuR1hE7dQS03BuvoBziTKnA9q0MvjxA/V10V3KscIN+xepW3AXJWTCCa3jCSi+dCf5vEBETw1tsfrKvhmyPUOcjV/5/Jj0WcAxuNx0ry8Xfrl7+ms1268UIVDdlkkuEtErPh0v3fp8RtZlCoYPYu+VxjfzRNZQNnz3uPLJqwgaobL+Jy02cGCASMySqSTOz9D4/Xrsnd9I5iwizWT+Q20wFFRnGempc21gNhP9PZ+CAsfN/5dvp1vntrRJJqBkkmwK3Hhnn62zk6vgRMIhCgQJdAl767UBcwHyMwCdsHE/PCafdO2pVqLQWCHcVkjL+gkzOcmuJkaSy7sYGm5P3QJVRJ7/sZ+dR+6DUJzSAf9tcN8ezxf3ERK/ygA7P+3865VORjkjW+Uua6WSNFsFfP+HfVmg4g0K5MFUC9uT2IQUfB5pXzRD31x8eSOMqlgqZP9bWcXMO5DgQQuy0aPhVusBNQw1PCK+2NiM0v2c2V8sJvS8YT4ytFdMrRXNJg663wFkJZogaIkQ5xF16BvNcNYp7ga9jwF1sXXb2Wa0Dx1HdQWMDiI8zA==
    wifi_guest_password: AgDnpqLu0GGDg4nlp5dMv4tAduxKWbRJgxw5cFBRLzpdGR2owJ1ZMllDexlpGTYoS07aD8P16L/SPNNUNLatb4y/dwpOLxFkQkbcMR+4esE4Wvn+wvOxvY6pFEEOSpZfrlRIuQObL88NgjyFjmoNCOsrqdynh8VkN7HcOQezufhHoPODa1nsve2EOnt7Tv+aJT1ZRXPzgLp2sopGtHMGM7gdkirghaX2EfgppTKrh6pA0kbAE8PELqwwsgZyuD6orzqoQWkEC9PRtp+NpqlVrVV8mrd7qZvUanKrAq1tuPBGr1sfyC+azeGQZAumblp8oVuUvb0Qz5lG+ZBBrV/c31nkIfGmilynVaCcz2LNa1pPoaIqHaf1Lg2JCYqYjENN3WjoVzC8I1AJLPrltVjJGMBxzm9WsbJ4gxBwLLc46f2e3y4csjZnQyM6LZL2B2gtqLu6mXhC6eTinWLDGzMYLRZfQN0z2iAvIT8UD0JesfD3OaS3vWtX94tZcIa3WfD86kUjF+x1UuLR7gFWbSd5XEaeiYR9jWZvdLaeKZ+nLq4zpo0MyVg2zc0wmT+tdrYrNZ6lOqEiIoTcoDBzfTWn1tGmjPdzpGpS4hNUAoFR2vu65xSpYhgEr8atmdvTHMeFEaBnLFevGn0Ixbh8muPh8s5/zH6GybTf+2TVeOoaPlirmFIDoOHEi373g4rUW/Rk5esUrmAuYFUXxE3W8N68v37FqAm6ag==
    xiaomi_cloud_password: AgAJcv9vZvcmF3dYX/xaHB7WIAyFjvaGjVsVykyvZSVTk+peiCGMPUmEZ9ydNnBvPAB+YZG9x3eyqP0Yn3wOI88Qph0rC3wH++D485kEPesBPsrhcVSVIGlAUQ+oGOk7JUDoq3T3GS0gfP071064yZAp8kH0Mi/UZNC8pKWEScQhBo061Naq+UI8OQY/2yKx4JHDTIWorv/61mObaflxw8v1rnyR1hPyzXmDC0/VM3SoRhTZY+wHLHCl0n/f5QU+tU2+TZaHIbuKYfBEXoJniGnNlI74236aZ4UdnX/PX7p2yF8pox4fic46bn7OhEPpRIhSZVZgoIJcQFhShqMuUMdyoM7N+Hh8bsRxiZL4QSwHJWZTQeXAsngWjnzgC7Gh4s9JJxMnlbZGL2WXKiNzBrD/plpQeOiShQGf2VsF2gUREtpH5ZPwUd+H3JgDz010Xv451PRi3sTzWAcN86ScqNPmYNC6FF8q5bu4+YmxomN9iVBr1Xm0NMIVzHjer/TlZgQca8aSgye+TUtjkoqcW9qhnhXqlEqAR2/HYMhZ384kCv0lN3CVjFQLGV6BCKWkQAJ5R9xHG1ZX0kH+v71why2CIZcJ0dCRayd0RdTvmLVDOgNguR72VWXXmj0rKRNAs+eLgqOa2T7YCGxoEXiLoaRu3HvLwh18HxnSsHSjGLCCAF+UoF0zCLbGWJIQIcEnbFtLLeD3VDOAiuUPoAzkH8ix
    xiaomi_cloud_username: AgAbhK9jR6q/0/v0NnqwMcm8dhUOwbpI5qDXpnSNfAyHEWO9CjOSOKjhMfMjpUc7xMlm/6cjaZiHVWx6DvjbKJXDj78LGYVF+klYVVCB478Z/kdv0bqTaqtzWp87IrPHB6p0KPwtHW3Gqk1pTALR9BDt7pCp5ZWWAAOp6tDLbo+evT7yMY3hpZeB2YR9L0irDr4LXWdSn0Cueb0IPTNF9tzsH9a1kPSxE5huQlOgjLxLqqb8i0Xk7MJe3r2qsXGigSjA2uPn3QrpPfkrPZGqgu19oPO/+3QOc23b92z/mE88v9JProkbK9vQ71aoTUDB9SQ9cKaXruR5jFIXCzJf2Od4O/ER5j6QpA4Ty/roebVurPsizudUQ5J8y3a/IYVBvm2HLg+m6Oisd6rh/SWKjzrJMMFnmxCLAL3Op1TiED2bb+GJAdmZMQBN+3O13PsHjWQvBLRgo+uAtOOP4c1qCp1udRgdzwsisLYHqAjr4gdbqG9H4eR0mU1CBJnHKnweymD702ONhBUwa5Gsji9vQk2/AoYoYj/QZJ1MGTdcZJgl2ZFGp7icrzWqSRW+mhjDJo3eXURSX2yJmzYw+QMpkBxb3FNbW0Kl/FFB4qwfreY+DDH4jZSV+UpLi8Zr5xXj3CFa8l/rK2r3EChYmPvONACuRZrzN13Je9DmjY9fvZYrVgbrPtpttPXPf6+lhDa5DEUp2ajwLqKCVeCRwZwcPGX5
    xiaomi_vacuum_s6_token: AgDKLLcePO/KrGvWf9c5xU/Bdbet0JTEuuIUF4JrQtZ81jI38yjp1NtDPDrCJFSLPMVBzcPop1jA7oPnB9KrCEokNA/vAKs2I+gM6ez6D3AjK/QSZn2/C1XIATpWX9Gq/NLnPd+ZSZAxMLC5LzwP2ZBHzbQ9K0D2B3V8xfUDU+ySzfypOq309Z0/TJ/4kTr/krt5A/UJ7rip5eQBYVnEOlCPJwqGwscMIFqQCBuOFo9CyqQlyghjScY4O/lYEFoQFRtne+LNFjOGtI3/vGLrVXQ1PiZgphj8HvSNqnAiXuLY9jxTIqO2j+7H6sBYtOtDZhhytg1uZv+GLyAyLolHz8X0dWLHrkddWVwhUR9NTUyFPVvoHbjU/+UnHWqPG3oEisLTCoNvOT1PC/FcTkMrarW+sY5jYayq64PZjFDjYoZFo/Um9sOKI9CNlGIqmlNEegDpy79fkTCt/8N9F/cq9YBiQIV3Gvpj6tTWXbUniwaJrkvYIBppxam1QpsmhAhnM6xf3j1xhsA/2wVAoW4BEDkDYWQhrLd1yFAHc/D1nrXy0zPTaPqmwSB6iJ1k/t1cvaJVQffTCka4Ad1X9HJ2zsyPgS9nuBdZJqlpAdjOhOm78IQRuC99rLfvZOwOQAhHaWM3rRrK/ffDSXFUOUOTDiFjg6G4uXQ9jLLsGB6XRJno5FhcOhEWX5QKV9Uvk4EGSuBrTALPWfrXQigDzDtNUrLr0cbTfpHYzPz9vgQMeau7vA==
  template:
    data:
      secrets.yaml: |-
        db_url: postgresql://{{ index . "postgresql-username" }}:{{ index . "postgresql-password" }}@home-assistant-postgresql-hl/home-assistant
        home_zipcode: {{ index . "home_zipcode" }}
        home_number: {{ index . "home_number" }}
        home_city: {{ index . "home_city" }}
        home_latitude: {{ index . "home_latitude" }}
        home_longitude: {{ index . "home_longitude" }}
        nvidia_shield_ip: 10.0.30.60
        xiaomi_cloud_password: {{ index . "xiaomi_cloud_password" }}
        xiaomi_cloud_username: {{ index . "xiaomi_cloud_username" }}
        xiaomi_vacuum_s6_token: {{ index . "xiaomi_vacuum_s6_token" }}
        wifi_guest_password: {{ index . "wifi_guest_password" }}
    metadata:
      labels:
        app: home-assistant
      name: secrets

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: home-assistant-postgresql
  labels:
    app: home-assistant-database
spec:
  replicas: 1
  serviceName: home-assistant-postgresql-hl
  selector:
    matchLabels:
      app: home-assistant-database
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: home-assistant-database
    spec:
      containers:
        - name: postgres
          image: docker.io/postgres:14
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "home-assistant"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: home-assistant-postgresql-secret
                  key: postgresql-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: home-assistant-postgresql-secret
                  key: postgresql-password
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "$POSTGRES_USER" -h 127.0.0.1 -p 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "$POSTGRES_USER" -h 127.0.0.1 -p 5432
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits: {}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: home-assistant
                namespaces:
                  - home-automation
                topologyKey: kubernetes.io/hostname
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: freenas-iscsi-manual-csi
        resources:
          requests:
            storage: 100Gi

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: home-assistant-database
              topologyKey: "kubernetes.io/hostname"
      initContainers:
        - name: postgresql-isready
          image: "docker.io/postgres:14"
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: home-assistant-postgresql-secret
                  key: postgresql-username
          command:
            - "sh"
            - "-c"
            - until pg_isready -U ${POSTGRESQL_USERNAME} -h home-assistant-postgresql-hl -p 5432 ;
              do sleep 2 ; done
      containers:
        - name: home-assistant
          image: "ghcr.io/x-real-ip/home-assistant:latest"
          imagePullPolicy: Always
          securityContext:
            privileged: true
          ports:
            - containerPort: 8123
              protocol: TCP
            - containerPort: 5683
              protocol: UDP
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "2000"
          livenessProbe:
            httpGet:
              path: /manifest.json
              port: 8123
          readinessProbe:
            httpGet:
              path: /manifest.json
              port: 8123
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          volumeMounts:
            - name: home-assistant-config
              mountPath: /config/.storage
              subPath: .storage
            - name: home-assistant-config
              mountPath: /config/www
              subPath: www
            - name: home-assistant-config
              mountPath: /config/custom_components
              subPath: custom_components
            - name: secrets
              mountPath: /config/secrets.yaml
              subPath: secrets.yaml
          resources: {}
      volumes:
        - name: home-assistant-config
          persistentVolumeClaim:
            claimName: pvc-nfs-home-assistant-config
        - name: secrets
          secret:
            secretName: secrets
      imagePullSecrets:
        - name: github-registry-creds

---
kind: Service
apiVersion: v1
metadata:
  name: home-assistant-postgresql-hl
  labels:
    app: home-assistant-database
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  selector:
    app: home-assistant-database
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: 5432

---
kind: Service
apiVersion: v1
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  selector:
    app: home-assistant
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8123

---
kind: Service
apiVersion: v1
metadata:
  name: home-assistant-coiot
  labels:
    app: home-assistant
spec:
  selector:
    app: home-assistant
  type: LoadBalancer
  loadBalancerIP: 10.0.100.243
  externalTrafficPolicy: Local
  ports:
    - name: coiot
      protocol: UDP
      port: 5683
      targetPort: 5683

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: home-assistant-private
  labels:
    app: home-assistant
spec:
  ingressClassName: nginx-private
  rules:
    - host: home-assistant.lan.stamx.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 80

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: home-assistant-public
  labels:
    app: home-assistant
spec:
  ingressClassName: nginx-public
  rules:
    - host: home-assistant.stamx.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 80
  tls:
    - hosts:
        - home-assistant.stamx.nl
      secretName: tls-wildcard-stamx-nl
