---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-home-assistant-config
  labels:
    app: home-assistant
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-nfs-home-assistant-config
