---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-iscsi-prowlarr-config
  namespace: media
  labels:
    app: prowlarr
spec:
  storageClassName: freenas-iscsi-manual-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-iscsi-prowlarr-config
