---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-iscsi-prowlarr-config
  labels:
    app: prowlarr
spec:
  storageClassName: "freenas-iscsi-manual-csi"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: xfs
    volumeHandle: pv-iscsi-prowlarr-config
    volumeAttributes:
      portal: truenas-master.lan.stamx.nl:3260
      iqn: iqn.2005-10.org.freenas.ctl:prowlarr-config
      lun: "0"
      node_attach_driver: iscsi
      provisioner_driver: node-manual
