---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../postgres/base

namePrefix: authentik-

labels:
  - includeSelectors: true
    pairs:
      app-instance: authentik-postgresql

patches:
  - target:
      kind: ConfigMap
      name: postgresql-env
    patch: |-
      - op: replace
        path: /data/POSTGRES_DB
        value: authentik
      - op: replace
        path: /data/POSTGRES_USER
        value: authentik
  - target:
      kind: StatefulSet
      name: postgresql
    patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 20Gi
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/volumeName
        value: authentik-pv-iscsi-postgresql-db
      - op: replace
        path: /spec/template/spec/containers/0/env/0/valueFrom/secretKeyRef/name
        value: authentik-postgresql-secret
  - target:
      kind: SealedSecret
      name: postgresql-secret
    patch: |-
      - op: replace
        path: /spec/template/metadata/name
        value: authentik-postgresql-secret
      - op: replace
        path: /spec/encryptedData/POSTGRES_PASSWORD
        value: AgAS147+JspZdzNyRIPB+tCKPkK+lC19AB5UAsNKA1+UzGcs6oRtFD+J7ZAm0NOs/L1wjwzGn8nSZdfN3b5ODcxTV1Rh/KgM7j2DOxmQ1ZWD2Pjr6zoWf1eV2Hv9G4O6aE872ZIXfn1NIiWdmyt5XgFEGc2p4Cs5SGyg+IDNsGWizRLuw3jSg6uQs5ZDMNwGyvYKNP21531L8wywoUXFcA8A7f6559dZ7klxF+kWOx7FxZgYexxbThjGvDgCB5/C8Hqnox1jrDe5ab76Q69APd8fe82mSzoRW8c5c26pduhJacKfKZ6yR0RlMCeY27wjtqbSKYXtXeloYCyFRCA2dnRjv+c3QJXeApz98/jVNMybDLRUXpvxwwoBGDEl+sKku6UBNzJ9YkisKAFDpVAntwkwGLR5K2gYLMTFpYQNfHbLKLD7uhvgydIxuOr7HTLuUK7AkI1BOuJZq49ES8fpRy9tdI1m9wvmkXnTkrGosXkEMVWte24W/7eVeD/3V1TjAP7YcrFlWKsIO1QByAz6Z/VpT1X1QAc/HWKWpLD7BvhKarm4FH4uUUOXIGCKLIEkbLTECeLA/Upa/ndG9KQOUpzqrrIt9lXTLaKnPV1INBJZ3/De6eFOZXv0fjb496oKWU2dKDAWKxQr7xXpHW7qFFUITqWwJ9hXnGRRLaV2LQKTUNx5vKLbttzCXqa9fODLQ+v9uVgfz4PkqCKTvwh+mFbIbvhdXy10lwyRDujLcwlMrmWfcDgUM6uHSQ6O7SQOt7sI
  - target:
      kind: PersistentVolume
      name: pv-iscsi-postgresql-db
    patch: |-
      - op: replace
        path: /spec/capacity/storage
        value: 20Gi
      - op: replace
        path: /spec/csi/volumeAttributes/iqn
        value: "iqn.2005-10.org.freenas.ctl:authentik-db"
