---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../postgres/base

namePrefix: authentik-

labels:
  - includeSelectors: true
    pairs:
      app-instance: authentik-postgresql

patches:
  - target:
      kind: ConfigMap
      name: postgresql-env
    patch: |-
      - op: replace
        path: /data/POSTGRES_DB
        value: authentik
      - op: replace
        path: /data/POSTGRES_USER
        value: authentik
  - target:
      kind: StatefulSet
      name: postgresql
    patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 20Gi
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/volumeName
        value: authentik-pv-iscsi-postgresql-db
      - op: replace
        path: /spec/template/spec/containers/0/env/0/valueFrom/secretKeyRef/name
        value: authentik-postgresql-secret
  - target:
      kind: SealedSecret
      name: postgresql-secret
    patch: |-
      - op: replace
        path: /spec/template/metadata/name
        value: authentik-postgresql-secret
      - op: replace
        path: /spec/encryptedData/POSTGRES_PASSWORD
        value: AgA7ZPWAnxm5PhtPd+0oZpUaToCFzne6d5+7nNGpIZoXw2gmElszkmmDVWIiy82U/54+F/+5XTi5V77d90DWlxR6n7rVWC2dHfFtIfFzOvDOJT8zQcUATFrqOrvfou6zAYXbGi8VYz5JmmZONDRL7XxmbZkGPpUhVCERhreULOOf3+dPWd1CRk/Xcc0XdDwb88sUKFvc+RpqSMp0wLj9nFno5skPs/Q7W2ot37lPNIkKP6HhmdoRR+O9d0Jv6iJZTGCCAxLpUiZj/YPf1x5rZPGFOkKUZUjVBurYvoQnIJWh3Q06sFMEJHf7y2ZOKndE8fYeyFYhopk+CzuLbzub/+q1JQb3LAEIfPuB4CKaO6iCyQVFI40YNIo9JI+fKvGMmHXoJDbm2Rco668H6iRFO2zr6unn9eplTJTnsJ4Hw+r0vPaPOgjbwG57OoRLcKajvJl+icJWinuk/OLKsyZlvHfaU4Y5BhweyBvucixBDkPTU0qaQhkR9oFNHC+12ZErHlcc+uaTM3+QkYAxVbpuhSxDOk7mgSlVP/N0cwNsJUiNUsQ/3hJ9HDYk54MEPWHGNmgBkdISDb6GFeegbih5lZ2bta5rFrqm3pbWPWmMy+IKobOhnQW9yEpiAiOPo07YqArQlKRoKcArnZ/sW71v9c5gDOj0ieh2xkoxMpNeE85JS/hDj27kTD0OheU9882UVBJeherqsLVCzXNZrBiLLubP5ByZdkeAYEtfc7Yh/wsGkI4NyauwrSmsEdLjNGvaFPkw
  - target:
      kind: PersistentVolume
      name: pv-iscsi-postgresql-db
    patch: |-
      - op: replace
        path: /spec/capacity/storage
        value: 20Gi
      - op: replace
        path: /spec/csi/volumeAttributes/iqn
        value: "iqn.2005-10.org.freenas.ctl:authentik-db"
