---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-iscsi-transmission-config
  labels:
    app: transmission
spec:
  storageClassName: "freenas-iscsi-manual-csi"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: xfs
    volumeHandle: pv-iscsi-transmission-config
    volumeAttributes:
      portal: truenas-master.lan.stamx.nl:3260
      iqn: iqn.2005-10.org.freenas.ctl:transmission-config
      lun: "0"
      node_attach_driver: iscsi
      provisioner_driver: node-manual

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-downloads
  labels:
    app: transmission
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-downloads
    volumeAttributes:
      server: truenas-master.lan.stamx.nl
      share: /mnt/ssd/containers/k8s/transmission-downloads
      node_attach_driver: nfs
      provisioner_driver: node-manual
