---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-downloads
  labels:
    app: transmission
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: pv-nfs-downloads

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-iscsi-transmission-config
  labels:
    app: transmission
spec:
  storageClassName: freenas-iscsi-manual-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-iscsi-transmission-config
