---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: transmission-vpn-cred
  labels:
    app: transmission
spec:
  encryptedData:
    OPENVPN_PASSWORD: AgDhcF2An3Lp/LyJPtSsDOkXl8KT1DOqeWN2qNQGXZeW36se9n54zx54YcpSwvshpWsb2lONsPDnK4hycYWOngmhRRIdeOmEbieOhl1ia/bxlqSrhy73dvQMN+N8nPFLanuEByjrIdb0V4SN+8k1nD9ChfSmtbNVNeYdGXagUXm1Raj23cYICARjO4MzwWF02UjJ+m6ZzgLBRA32bOw7HKKnsecuhsRZ2vtfz1I75NZSe2ZjuCWPTEKYsexofu9V1JieuuQWYB+iuc4W887xj+54Z6DRGzSUNNse/DJciT76mWjU3+bljGL2MEAIWsWc0B2duav05feLFueqxw5W+nwy48epxFhpE//sqFkD/C1nTS5bHiaQPk7O2VjM0RBU9qmiUAVHtmugzvgTki1NFrxKUOZjByN57XQ25tUzvi7sxdhYgKQi96ERmgJY1c6LSZhTYLTL3HSbNzmpuwOsvwUkSpperCGif6G+OgHsVPt+Jq3PbFG04kT1/5pCoFWzQHAT4sXzXh73N80JYvj/Fko33zo3I0eBnS+4nQ20Jwn/jSMxlmvL/NqDd2sDiaHpoPaMEgP19YRb1hiGcpel3nMmngeX9WzWqNJSWDmpYOgKdH+xfnR0wdSRuae5Df2ZXRaiMBRaZPzwABT0Yg6rcLyBhxcxbO2Xkkeiuz2wZLjoZvK0DpHjgZVM23b9WWEy9WuF46HNSZO1qpp2kNmvDmPnUcekgA2xACo=
    OPENVPN_USERNAME: AgApqotmd1kXCWBOrp7VRLvKHnhbFUOwi1+nOFlD+qt8PxrybaATsjy/KFDZx0TSgcSA49zL4BZ5lAto3kXloEU+jZ6e1mChP/J9Sx+ILZyK0DIz7IWL41av0smXORbbMaMGJA37VDx24M4+bHwPqWYM8JPX5Y6JE8lQeMX+nitYso0ZXVBg2/2LL3UO0yHihoRvwGzO+ByEuAwfcX7VfYSMQQZxrBI21YjcctYyuUnapgq1hU5s+eTHtgJiSqh8HrKZL744cyWVXneUkBX5xJ2NZyjDd4F2jC0AdNF8WvEW08SE0K3Ik1canRP+Qvl1kVHgVg/0RIKAAdgq9JS92tgocJKPSuG6IO1USaEEC65qQgpFkOcCZ/ijSMUJ2jtAFAd2lMtbDgZGKOeTDe4CdvsRLooycRDDxafZQASwoWFmv88EHIw3sxMYVUW2wwp74t03Ke+JThgpcA+ZrCYjdVQA7f1j5dffgvXyGNu2yLu1O2U6EcKY0IYsU4Gnsrg6J4O0ThqHpmEo+0iRVZ1GEuHoFthtpJBOxVi1zjfm/rWC77PCiS4/vOQM3qV2P6O1mePO7o2XXy2rxpekjM2RWrajMfhU8SxwSc2/eI74XXTka4e1HF6uQo92dtVSdhq8Ea2KS3tffNehkMCTJHT4SR/fPH68kmjNEWGfLU0WM5Z6ltI0ErCqj6wpGRDxph9UmixGIpNu0wH/MpIhY8EQIENuPD8qW11iTQQ=
  template:
    metadata:
      name: transmission-vpn-cred
      labels:
        app: transmission
    type: Opaque
