---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-iscsi-syncthing-config
  labels:
    app: syncthing
spec:
  storageClassName: "freenas-iscsi-manual-csi"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: xfs
    volumeHandle: pv-iscsi-syncthing-data
    volumeAttributes:
      portal: truenas-master.lan.stamx.nl:3260
      iqn: iqn.2005-10.org.freenas.ctl:syncthing-config
      lun: "0"
      node_attach_driver: iscsi
      provisioner_driver: node-manual

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-iscsi-syncthing-config
  labels:
    app: syncthing
spec:
  storageClassName: freenas-iscsi-manual-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-iscsi-syncthing-config

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-syncthing-data
  labels:
    app: syncthing
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 600Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-syncthing-data
    volumeAttributes:
      server: truenas-master.lan.stamx.nl
      share: /mnt/ssd/webdav
      node_attach_driver: nfs
      provisioner_driver: node-manual

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-syncthing-data
  namespace: tools
  labels:
    app: syncthing
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 600Gi
  volumeName: pv-nfs-syncthing-data

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      containers:
        - name: syncthing
          image: docker.io/syncthing/syncthing:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "2000"
          ports:
            - name: webui
              containerPort: 8384
              protocol: TCP
            - name: filetransfer
              containerPort: 22000
              protocol: TCP
            - name: quic
              containerPort: 22000
              protocol: UDP
            - name: discovery
              containerPort: 21027
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /rest/noauth/health
              port: 8384
            initialDelaySeconds: 60
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /rest/noauth/health
              port: 8384
            initialDelaySeconds: 10
            periodSeconds: 30
          resources: {}
          volumeMounts:
            - mountPath: /var/syncthing
              name: config
            - mountPath: /var/shared
              name: data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pvc-iscsi-syncthing-config
        - name: data
          persistentVolumeClaim:
            claimName: pvc-nfs-syncthing-data

---
apiVersion: v1
kind: Service
metadata:
  name: syncthing
  labels:
    app: syncthing
spec:
  selector:
    app: syncthing
  type: LoadBalancer
  loadBalancerIP: 10.0.100.244
  ports:
    - name: webui
      protocol: TCP
      port: 8384
      targetPort: webui
    - name: filetransfer
      protocol: TCP
      port: 22000
      targetPort: filetransfer
    - name: quic
      protocol: UDP
      port: 22000
      targetPort: quic
    - name: discovery
      protocol: UDP
      port: 21027
      targetPort: discovery

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: syncthing
  labels:
    app: syncthing
spec:
  ingressClassName: nginx-private
  rules:
    - host: syncthing.lan.stamx.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: syncthing
                port:
                  name: webui
