---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-iscsi-syncthing-config
  labels:
    app: syncthing
spec:
  storageClassName: freenas-iscsi-manual-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-iscsi-syncthing-config
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-syncthing-data
  namespace: tools
  labels:
    app: syncthing
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 600Gi
  volumeName: pv-nfs-syncthing-data
