---
apiVersion: v1
kind: Service
metadata:
  name: p1-relay
  labels:
    app.kubernetes.io/name: p1-relay
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: p1-relay
  ports:
    - name: p1-stream
      port: 8888
      targetPort: p1-stream
      protocol: TCP
    - name: health
      port: 9090
      targetPort: health
      protocol: TCP
