apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: ghcr.io/x-real-ip/protonmail-bridge
  newTag: 00f9ee5ad2cb7ce89e9414a9fb5540b2e48f8a4d

labels:
- includeSelectors: true
  pairs:
    storage: truenas
