---
apiVersion: v1
kind: ConfigMap
metadata:
  name: depart-config
  labels:
    app: depart
data:
  BACKEND_URL: "http://depart-api:8080"
  PORT: "8080"
  APP_TITLE: "Depart"
  DOCUMENTS_PATH: "/data/documents"
  LOG_LEVEL: "info"
