---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgresql
  - configmap.yaml
  - sealedsecret.yaml
  - persistentvolume.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
