name: Check releases

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-releases:
    uses: x-real-ip/github-actions/.github/workflows/new-release-issue.yaml@main
    secrets:
      PAT: ${{ secrets.PAT }}
    strategy:
      matrix:
        include:
          - name: ingress-nginx
            type: release
            target: ghcr.io/kubernetes/ingress-nginx
            bump: false
            bump_type: ""
            image: ""
          - name: immich
            type: release
            target: ghcr.io/immich-app/immich
            bump: true
            bump_type: kustomize
            image: "ghcr.io/immich-app/immich-server ghcr.io/immich-app/immich-machine-learning"
          - name: dsmr-reader
            type: image
            target: ghcr.io/xirixiz/dsmr-reader-docker
            bump: true
            bump_type: kustomize
            image: "ghcr.io/xirixiz/dsmr-reader-docker"
          # - name: democratic-csi
          #   type: image
          #   target: ghcr.io/democratic-csi/democratic-csi
          #   bump: true
          #   bump_type: kustomize
          #   image: "ghcr.io/democratic-csi/democratic-csi"
          - name: frigate
            type: release
            target: ghcr.io/blakeblackshear/frigate
            bump: false
            bump_type: kustomize
            image: ""
          - name: go2rtc
            type: release
            target: AlexxIT/go2rtc
            bump: false
            bump_type: kustomize
            image: ""
          - name: MetalLB
            type: release
            target: metallb/metallb
            bump: false
            bump_type: kustomize
            image: ""
          - name: Kubernetes Node Feature Discovery
            type: release
            target: kubernetes-sigs/node-feature-discovery
            bump: false
            bump_type: kustomize
            image: ""
          - name: Omada Controller
            type: release
            target: mbentley/docker-omada-controller
            bump: false
            bump_type: kustomize
            image: ""
          - name: peperless
            type: release
            target: ghcr.io/paperless-ngx/paperless-ngx
            bump: false
            bump_type: kustomize
            image: ""
          - name: Syncthing
            type: release
            target: syncthing/syncthing
            bump: false
            bump_type: kustomize
            image: ""
          - name: Uptime Kuma
            type: release
            target: louislam/uptime-kuma
            bump: false
            bump_type: kustomize
            image: ""
          - name: Vaultwarden
            type: release
            target: dani-garcia/vaultwarden
            bump: false
            bump_type: kustomize
            image: ""
          - name: zwavejs2mqtt
            type: image
            target: ghcr.io/zwave-js/zwave-js-ui
            bump: true
            bump_type: kustomize
            image: ghcr.io/zwave-js/zwave-js-ui
          - name: radicale
            type: release
            target: tomsquest/docker-radicale
            bump: false
            bump_type: kustomize
            image: ""
          - name: Transmission OpenVPN
            type: release
            target: haugene/docker-transmission-openvpn
            bump: false
            bump_type: kustomize
            image: ""
    with:
      name: ${{ matrix.name }}
      target: ${{ matrix.target }}
      type: ${{ matrix.type }}
      bump: ${{ matrix.bump }}
      bump_type: ${{ matrix.bump_type }}
      image: ${{ matrix.image }}
